BANNER   fcc   "          **** DYNACALC ****"
         fcb   0

         fcc   "        Version Number - 4.7:3"
         fcb   0
M0D8F    fcc   "Copyright (C) 1982 by Scott Schaeferle"
         fcb   0
M0D91    fcc   "    Customized for the ADDS Viewpoint   "
M0D91    fcc   "    Customized for the ANSI             "
         fcb   0

M0DA9    fcc   "        (Press any key to continue)"
         fcb   $00
M0DC8    fcc   "                   (Loading file...)"
         fcb   $00

