BANNER   fcc   "          **** DYNACALC ****"
         fcb   0

         fcc   "        Version Number - 4.7:3"
         fcb   0
         fcc   "Copyright (C) 1982 by Scott Schaeferle"
         fcb   0
         fcc   "    Customized for the ANSI             "
         fcb   0
         fcc   "        (Press any key to continue)"
         fcb   0
MLOAD    fcc   "                    Loading "
         fcb   0

