         fcb   $59,$A6,$59,$00,$00,$00,$00,$00,$87,$41,$0D,$09,$40,$01,$04,$09
* copy right starts at $10
         fcc   "DYNACALC, Version 4.7:3              "
         fcc   "Copyright (C) 1982,1983 by Scott Schaeferle."
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $87
         fcb   $09
         fcb   $43 C
         fcb   $01
         fcb   $02
         fcb   $09
         fcb   $80
         fcb   $20
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $83
         fcb   $09
         fcb   $83
         fcb   $20
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $83
         fcb   $09
M0080    fcb   $82
         fcb   $20
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
