* Texts are shortened to max 32 characters per line
HELPS    fcc   "A  set Attributes"
         fcb   $0D
         fcc   "B  Blank current cell"
         fcb   $0D
         fcc   "C  Clear entire worksheet"
         fcb   $0D
         fcc   "D  Delete current column or row"
         fcb   $0D
         fcc   "E  Edit contents, current cell"
         fcb   $0D
         fcc   "F  set Format of current cell"
         fcb   $0D
         fcc   "I  Insert new column or row"
         fcb   $0D
         fcc   "K  enter Keysaver mode"
         fcb   $0D
         fcc   "L  Locate specified label,"
         fcb   $0D
         fcc   /   ?="Wild card" character/
         fcb   $0D
         fcc   /   @="Don't ignore case" char./
         fcb   $0D
         fcb   $0A
         fcc   "   Hit any key to see page 2"
         fcb   $11
         fcc   "M  Move column or row"
         fcb   $0D
         fcc   "P  Print sheet: file or printer"
         fcb   $0D
         fcc   "Q  Quit and go to Sleep or OS-9"
         fcb   $0D
         fcb   $52 R
         fcb   $20
         fcb   $20
         fcb   $52 R
         fcb   $65 e
         fcb   $70 p
         fcb   $6C l
         fcb   $69 i
         fcb   $63 c
         fcb   $61 a
         fcb   $74 t
         fcb   $65 e
         fcb   $20
         fcb   $28 (
         fcb   $63 c
         fcb   $6F o
         fcb   $70 p
         fcb   $79 y
         fcb   $29 )
         fcb   $20
         fcb   $63 c
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $28 (
         fcb   $73 s
         fcb   $29 )
         fcb   $0D
         fcb   $53 S
         fcb   $20
         fcb   $20
         fcb   $63 c
         fcb   $61 a
         fcb   $6C l
         fcb   $6C l
         fcb   $20
         fcb   $53 S
         fcb   $79 y
         fcb   $73 s
         fcb   $74 t
         fcb   $65 e
         fcb   $6D m
         fcb   $20
         fcb   $66 f
         fcb   $75 u
         fcb   $6E n
         fcb   $63 c
         fcb   $74 t
         fcb   $69 i
         fcb   $6F o
         fcb   $6E n
         fcb   $0D
         fcb   $54 T
         fcb   $20
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $74 t
         fcb   $20
         fcb   $63 c
         fcb   $6F o
         fcb   $6C l
         fcb   $75 u
         fcb   $6D m
         fcb   $6E n
         fcb   $20
         fcb   $6F o
         fcb   $72 r
         fcb   $20
         fcb   $72 r
         fcb   $6F o
         fcb   $77 w
         fcb   $20
         fcb   $54 T
         fcb   $69 i
         fcb   $74 t
         fcb   $6C l
         fcb   $65 e
         fcb   $73 s
         fcb   $0D
         fcb   $57 W
         fcb   $20
         fcb   $20
         fcb   $61 a
         fcb   $64 d
         fcb   $6A j
         fcb   $75 u
         fcb   $73 s
         fcb   $74 t
         fcb   $20
         fcb   $64 d
         fcb   $69 i
         fcb   $73 s
         fcb   $70 p
         fcb   $6C l
         fcb   $61 a
         fcb   $79 y
         fcb   $20
         fcb   $57 W
         fcb   $69 i
         fcb   $6E n
         fcb   $64 d
         fcb   $6F o
         fcb   $77 w
         fcb   $28 (
         fcb   $73 s
         fcb   $29 )
         fcb   $0D
         fcb   $0A
         fcb   $48 H
         fcb   $69 i
         fcb   $74 t
         fcb   $20
         fcb   $40 @
         fcb   $20
         fcb   $66 f
         fcb   $6F o
         fcb   $72 r
         fcb   $20
         fcb   $68 h
         fcb   $65 e
         fcb   $6C l
         fcb   $70 p
         fcb   $20
         fcb   $77 w
         fcb   $69 i
         fcb   $74 t
         fcb   $68 h
         fcb   $20
         fcb   $46 F
         fcb   $55 U
         fcb   $4E N
         fcb   $43 C
         fcb   $54 T
         fcb   $49 I
         fcb   $4F O
         fcb   $4E N
         fcb   $53 S
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $3E >
         fcb   $20
         fcb   $66 f
         fcb   $6F o
         fcb   $72 r
         fcb   $20
         fcb   $68 h
         fcb   $65 e
         fcb   $6C l
         fcb   $70 p
         fcb   $20
         fcb   $77 w
         fcb   $69 i
         fcb   $74 t
         fcb   $68 h
         fcb   $20
         fcb   $45 E
         fcb   $52 R
         fcb   $52 R
         fcb   $4F O
         fcb   $52 R
         fcb   $53 S
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $47 G
         fcb   $20
         fcb   $66 f
         fcb   $6F o
         fcb   $72 r
         fcb   $20
         fcb   $67 g
         fcb   $65 e
         fcb   $6E n
         fcb   $65 e
         fcb   $72 r
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $68 h
         fcb   $65 e
         fcb   $6C l
         fcb   $70 p
         fcb   $00
         fcb   $53 S
         fcb   $65 e
         fcb   $74 t
         fcb   $20
         fcb   $61 a
         fcb   $74 t
         fcb   $74 t
         fcb   $72 r
         fcb   $69 i
         fcb   $62 b
         fcb   $75 u
         fcb   $74 t
         fcb   $65 e
         fcb   $73 s
         fcb   $3A :
         fcb   $0D
         fcb   $42 B
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $67 g
         fcb   $67 g
         fcb   $6C l
         fcb   $65 e
         fcb   $20
         fcb   $42 B
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $20
         fcb   $6F o
         fcb   $6E n
         fcb   $2F /
         fcb   $6F o
         fcb   $66 f
         fcb   $66 f
         fcb   $0D
         fcb   $44 D
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $67 g
         fcb   $67 g
         fcb   $6C l
         fcb   $65 e
         fcb   $20
         fcb   $44 D
         fcb   $65 e
         fcb   $67 g
         fcb   $72 r
         fcb   $65 e
         fcb   $65 e
         fcb   $2F /
         fcb   $72 r
         fcb   $61 a
         fcb   $64 d
         fcb   $69 i
         fcb   $61 a
         fcb   $6E n
         fcb   $20
         fcb   $6D m
         fcb   $6F o
         fcb   $64 d
         fcb   $65 e
         fcb   $0D
         fcb   $47 G
         fcb   $20
         fcb   $20
         fcb   $63 c
         fcb   $68 h
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $20
         fcb   $47 G
         fcb   $72 r
         fcb   $61 a
         fcb   $70 p
         fcb   $68 h
         fcb   $20
         fcb   $63 c
         fcb   $68 h
         fcb   $61 a
         fcb   $72 r
         fcb   $61 a
         fcb   $63 c
         fcb   $74 t
         fcb   $65 e
         fcb   $72 r
         fcb   $0D
         fcb   $48 H
         fcb   $20
         fcb   $20
         fcb   $64 d
         fcb   $65 e
         fcb   $6C l
         fcb   $65 e
         fcb   $74 t
         fcb   $65 e
         fcb   $20
         fcb   $48 H
         fcb   $65 e
         fcb   $6C l
         fcb   $70 p
         fcb   $20
         fcb   $6D m
         fcb   $65 e
         fcb   $73 s
         fcb   $73 s
         fcb   $61 a
         fcb   $67 g
         fcb   $65 e
         fcb   $73 s
         fcb   $0D
         fcb   $4C L
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $67 g
         fcb   $67 g
         fcb   $6C l
         fcb   $65 e
         fcb   $20
         fcb   $4C L
         fcb   $61 a
         fcb   $62 b
         fcb   $65 e
         fcb   $6C l
         fcb   $20
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $72 r
         fcb   $79 y
         fcb   $20
         fcb   $6D m
         fcb   $6F o
         fcb   $64 d
         fcb   $65 e
         fcb   $20
         fcb   $66 f
         fcb   $6C l
         fcb   $61 a
         fcb   $67 g
         fcb   $0D
         fcb   $4D M
         fcb   $20
         fcb   $20
         fcb   $72 r
         fcb   $65 e
         fcb   $2D -
         fcb   $77 w
         fcb   $72 r
         fcb   $69 i
         fcb   $74 t
         fcb   $65 e
         fcb   $20
         fcb   $28 (
         fcb   $4D M
         fcb   $6F o
         fcb   $64 d
         fcb   $69 i
         fcb   $66 f
         fcb   $79 y
         fcb   $29 )
         fcb   $20
         fcb   $73 s
         fcb   $63 c
         fcb   $72 r
         fcb   $65 e
         fcb   $65 e
         fcb   $6E n
         fcb   $0D
         fcb   $4F O
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $67 g
         fcb   $67 g
         fcb   $6C l
         fcb   $65 e
         fcb   $20
         fcb   $43 C
         fcb   $6F o
         fcb   $6C l
         fcb   $2E .
         fcb   $2F /
         fcb   $52 R
         fcb   $6F o
         fcb   $77 w
         fcb   $20
         fcb   $63 c
         fcb   $61 a
         fcb   $6C l
         fcb   $63 c
         fcb   $2E .
         fcb   $20
         fcb   $4F O
         fcb   $72 r
         fcb   $64 d
         fcb   $65 e
         fcb   $72 r
         fcb   $0D
         fcb   $50 P
         fcb   $20
         fcb   $20
         fcb   $63 c
         fcb   $68 h
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $50 P
         fcb   $72 r
         fcb   $69 i
         fcb   $6E n
         fcb   $74 t
         fcb   $65 e
         fcb   $72 r
         fcb   $20
         fcb   $70 p
         fcb   $61 a
         fcb   $72 r
         fcb   $61 a
         fcb   $6D m
         fcb   $65 e
         fcb   $74 t
         fcb   $65 e
         fcb   $72 r
         fcb   $73 s
         fcb   $0D
         fcb   $52 R
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $67 g
         fcb   $67 g
         fcb   $6C l
         fcb   $65 e
         fcb   $20
         fcb   $41 A
         fcb   $75 u
         fcb   $74 t
         fcb   $6F o
         fcb   $2F /
         fcb   $4D M
         fcb   $61 a
         fcb   $6E n
         fcb   $75 u
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $52 R
         fcb   $65 e
         fcb   $63 c
         fcb   $61 a
         fcb   $6C l
         fcb   $63 c
         fcb   $2E .
         fcb   $0D
         fcb   $53 S
         fcb   $20
         fcb   $20
         fcb   $72 r
         fcb   $65 e
         fcb   $70 p
         fcb   $6F o
         fcb   $72 r
         fcb   $74 t
         fcb   $73 s
         fcb   $20
         fcb   $53 S
         fcb   $69 i
         fcb   $7A z
         fcb   $65 e
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $77 w
         fcb   $6F o
         fcb   $72 r
         fcb   $6B k
         fcb   $73 s
         fcb   $68 h
         fcb   $65 e
         fcb   $65 e
         fcb   $74 t
         fcb   $0D
         fcb   $54 T
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $67 g
         fcb   $67 g
         fcb   $6C l
         fcb   $65 e
         fcb   $20
         fcb   $54 T
         fcb   $79 y
         fcb   $70 p
         fcb   $65 e
         fcb   $20
         fcb   $70 p
         fcb   $72 r
         fcb   $6F o
         fcb   $74 t
         fcb   $65 e
         fcb   $63 c
         fcb   $74 t
         fcb   $69 i
         fcb   $6F o
         fcb   $6E n
         fcb   $0D
         fcb   $57 W
         fcb   $20
         fcb   $20
         fcb   $63 c
         fcb   $68 h
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $63 c
         fcb   $6F o
         fcb   $6C l
         fcb   $75 u
         fcb   $6D m
         fcb   $6E n
         fcb   $20
         fcb   $57 W
         fcb   $69 i
         fcb   $64 d
         fcb   $74 t
         fcb   $68 h
         fcb   $28 (
         fcb   $73 s
         fcb   $29 )
         fcb   $00
         fcb   $44 D
         fcb   $65 e
         fcb   $6C l
         fcb   $65 e
         fcb   $74 t
         fcb   $65 e
         fcb   $20
         fcb   $63 c
         fcb   $6F o
         fcb   $6C l
         fcb   $75 u
         fcb   $6D m
         fcb   $6E n
         fcb   $2F /
         fcb   $72 r
         fcb   $6F o
         fcb   $77 w
         fcb   $3A :
         fcb   $0D
         fcb   $0A
         fcb   $43 C
         fcb   $20
         fcb   $20
         fcb   $64 d
         fcb   $65 e
         fcb   $6C l
         fcb   $65 e
         fcb   $74 t
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $63 c
         fcb   $75 u
         fcb   $72 r
         fcb   $72 r
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $20
         fcb   $43 C
         fcb   $6F o
         fcb   $6C l
         fcb   $75 u
         fcb   $6D m
         fcb   $6E n
         fcb   $0D
         fcb   $52 R
         fcb   $20
         fcb   $20
         fcb   $64 d
         fcb   $65 e
         fcb   $6C l
         fcb   $65 e
         fcb   $74 t
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $63 c
         fcb   $75 u
         fcb   $72 r
         fcb   $72 r
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $20
         fcb   $52 R
         fcb   $6F o
         fcb   $77 w
         fcb   $00
         fcb   $53 S
         fcb   $65 e
         fcb   $74 t
         fcb   $20
         fcb   $46 F
         fcb   $6F o
         fcb   $72 r
         fcb   $6D m
         fcb   $61 a
         fcb   $74 t
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $63 c
         fcb   $75 u
         fcb   $72 r
         fcb   $72 r
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $20
         fcb   $63 c
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $3A :
         fcb   $0D
         fcb   $0A
         fcb   $43 C
         fcb   $20
         fcb   $20
         fcb   $43 C
         fcb   $6F o
         fcb   $6E n
         fcb   $74 t
         fcb   $69 i
         fcb   $6E n
         fcb   $75 u
         fcb   $6F o
         fcb   $75 u
         fcb   $73 s
         fcb   $20
         fcb   $2D -
         fcb   $20
         fcb   $63 c
         fcb   $68 h
         fcb   $61 a
         fcb   $72 r
         fcb   $61 a
         fcb   $63 c
         fcb   $74 t
         fcb   $65 e
         fcb   $72 r
         fcb   $73 s
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $72 r
         fcb   $65 e
         fcb   $70 p
         fcb   $65 e
         fcb   $61 a
         fcb   $74 t
         fcb   $65 e
         fcb   $64 d
         fcb   $20
         fcb   $74 t
         fcb   $68 h
         fcb   $72 r
         fcb   $6F o
         fcb   $75 u
         fcb   $67 g
         fcb   $68 h
         fcb   $6F o
         fcb   $75 u
         fcb   $74 t
         fcb   $20
         fcb   $63 c
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $0D
         fcb   $44 D
         fcb   $20
         fcb   $20
         fcb   $44 D
         fcb   $65 e
         fcb   $66 f
         fcb   $61 a
         fcb   $75 u
         fcb   $6C l
         fcb   $74 t
         fcb   $20
         fcb   $2D -
         fcb   $20
         fcb   $75 u
         fcb   $73 s
         fcb   $65 e
         fcb   $20
         fcb   $77 w
         fcb   $69 i
         fcb   $6E n
         fcb   $64 d
         fcb   $6F o
         fcb   $77 w
         fcb   $20
         fcb   $66 f
         fcb   $6F o
         fcb   $72 r
         fcb   $6D m
         fcb   $61 a
         fcb   $74 t
         fcb   $0D
         fcb   $47 G
         fcb   $20
         fcb   $20
         fcb   $47 G
         fcb   $65 e
         fcb   $6E n
         fcb   $65 e
         fcb   $72 r
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $2D -
         fcb   $20
         fcb   $66 f
         fcb   $72 r
         fcb   $65 e
         fcb   $65 e
         fcb   $2D -
         fcb   $66 f
         fcb   $6F o
         fcb   $72 r
         fcb   $6D m
         fcb   $61 a
         fcb   $74 t
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $28 (
         fcb   $6C l
         fcb   $61 a
         fcb   $62 b
         fcb   $65 e
         fcb   $6C l
         fcb   $73 s
         fcb   $20
         fcb   $6C l
         fcb   $65 e
         fcb   $66 f
         fcb   $74 t
         fcb   $2C ,
         fcb   $20
         fcb   $6E n
         fcb   $75 u
         fcb   $6D m
         fcb   $62 b
         fcb   $65 e
         fcb   $72 r
         fcb   $73 s
         fcb   $20
         fcb   $72 r
         fcb   $69 i
         fcb   $67 g
         fcb   $68 h
         fcb   $74 t
         fcb   $29 )
         fcb   $0D
         fcb   $49 I
         fcb   $20
         fcb   $20
         fcb   $49 I
         fcb   $6E n
         fcb   $74 t
         fcb   $65 e
         fcb   $67 g
         fcb   $65 e
         fcb   $72 r
         fcb   $20
         fcb   $2D -
         fcb   $20
         fcb   $72 r
         fcb   $6F o
         fcb   $75 u
         fcb   $6E n
         fcb   $64 d
         fcb   $73 s
         fcb   $20
         fcb   $44 D
         fcb   $49 I
         fcb   $53 S
         fcb   $50 P
         fcb   $4C L
         fcb   $41 A
         fcb   $59 Y
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $6E n
         fcb   $65 e
         fcb   $61 a
         fcb   $72 r
         fcb   $65 e
         fcb   $73 s
         fcb   $74 t
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $74 t
         fcb   $65 e
         fcb   $67 g
         fcb   $65 e
         fcb   $72 r
         fcb   $0D
         fcb   $4C L
         fcb   $20
         fcb   $20
         fcb   $4C L
         fcb   $65 e
         fcb   $66 f
         fcb   $74 t
         fcb   $20
         fcb   $6A j
         fcb   $75 u
         fcb   $73 s
         fcb   $74 t
         fcb   $69 i
         fcb   $66 f
         fcb   $79 y
         fcb   $20
         fcb   $2D -
         fcb   $20
         fcb   $66 f
         fcb   $6F o
         fcb   $72 r
         fcb   $63 c
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $6E n
         fcb   $75 u
         fcb   $6D m
         fcb   $62 b
         fcb   $65 e
         fcb   $72 r
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $6C l
         fcb   $65 e
         fcb   $66 f
         fcb   $74 t
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $63 c
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $0D
         fcb   $0A
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $48 H
         fcb   $69 i
         fcb   $74 t
         fcb   $20
         fcb   $61 a
         fcb   $6E n
         fcb   $79 y
         fcb   $20
         fcb   $6B k
         fcb   $65 e
         fcb   $79 y
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $65 e
         fcb   $20
         fcb   $70 p
         fcb   $61 a
         fcb   $67 g
         fcb   $65 e
         fcb   $20
         fcb   $32 2
         fcb   $11
         fcb   $50 P
         fcb   $20
         fcb   $20
         fcb   $50 P
         fcb   $6C l
         fcb   $6F o
         fcb   $74 t
         fcb   $20
         fcb   $2D -
         fcb   $20
         fcb   $75 u
         fcb   $73 s
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $63 c
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $27 '
         fcb   $73 s
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $74 t
         fcb   $65 e
         fcb   $67 g
         fcb   $65 e
         fcb   $72 r
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $76 v
         fcb   $61 a
         fcb   $6C l
         fcb   $75 u
         fcb   $65 e
         fcb   $20
         fcb   $61 a
         fcb   $73 s
         fcb   $20
         fcb   $6E n
         fcb   $75 u
         fcb   $6D m
         fcb   $62 b
         fcb   $65 e
         fcb   $72 r
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $67 g
         fcb   $72 r
         fcb   $61 a
         fcb   $70 p
         fcb   $68 h
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $63 c
         fcb   $68 h
         fcb   $61 a
         fcb   $72 r
         fcb   $61 a
         fcb   $63 c
         fcb   $74 t
         fcb   $65 e
         fcb   $72 r
         fcb   $73 s
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $70 p
         fcb   $72 r
         fcb   $69 i
         fcb   $6E n
         fcb   $74 t
         fcb   $0D
         fcc   "R  Right justify - forces label"
         fcb   $0D
         fcc   "   to right of cell"
         fcb   $0D
         fcc   "$  Dollar - rounds DISPLAY to"
         fcb   $0D
         fcc   "   nearest cent"
         fcb   $00

         fcc   "Insert new column or row:"
         fcb   $0D
         fcb   $0A
         fcb   $43 C
         fcb   $20
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $73 s
         fcb   $65 e
         fcb   $72 r
         fcb   $74 t
         fcb   $20
         fcb   $6E n
         fcb   $65 e
         fcb   $77 w
         fcb   $20
         fcb   $62 b
         fcb   $6C l
         fcb   $61 a
         fcb   $6E n
         fcb   $6B k
         fcb   $20
         fcb   $43 C
         fcb   $6F o
         fcb   $6C l
         fcb   $75 u
         fcb   $6D m
         fcb   $6E n
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $61 a
         fcb   $74 t
         fcb   $20
         fcb   $63 c
         fcb   $75 u
         fcb   $72 r
         fcb   $72 r
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $20
         fcb   $70 p
         fcb   $6F o
         fcb   $73 s
         fcb   $69 i
         fcb   $74 t
         fcb   $69 i
         fcb   $6F o
         fcb   $6E n
         fcb   $0D
         fcb   $52 R
         fcb   $20
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $73 s
         fcb   $65 e
         fcb   $72 r
         fcb   $74 t
         fcb   $20
         fcb   $6E n
         fcb   $65 e
         fcb   $77 w
         fcb   $20
         fcb   $62 b
         fcb   $6C l
         fcb   $61 a
         fcb   $6E n
         fcb   $6B k
         fcb   $20
         fcb   $52 R
         fcb   $6F o
         fcb   $77 w
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $61 a
         fcb   $74 t
         fcb   $20
         fcb   $63 c
         fcb   $75 u
         fcb   $72 r
         fcb   $72 r
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $20
         fcb   $70 p
         fcb   $6F o
         fcb   $73 s
         fcb   $69 i
         fcb   $74 t
         fcb   $69 i
         fcb   $6F o
         fcb   $6E n
         fcb   $00
         fcb   $51 Q
         fcb   $75 u
         fcb   $69 i
         fcb   $74 t
         fcb   $3A :
         fcb   $0D
         fcb   $0A
         fcb   $4F O
         fcb   $20
         fcb   $20
         fcb   $6C l
         fcb   $65 e
         fcb   $61 a
         fcb   $76 v
         fcb   $65 e
         fcb   $20
         fcb   $44 D
         fcb   $59 Y
         fcb   $4E N
         fcb   $41 A
         fcb   $43 C
         fcb   $41 A
         fcb   $4C L
         fcb   $43 C
         fcb   $20
         fcb   $61 a
         fcb   $6E n
         fcb   $64 d
         fcb   $20
         fcb   $72 r
         fcb   $65 e
         fcb   $74 t
         fcb   $75 u
         fcb   $72 r
         fcb   $6E n
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $4F O
         fcb   $53 S
         fcb   $2D -
         fcb   $39 9
         fcb   $0D
         fcb   $0A
         fcb   $53 S
         fcb   $20
         fcb   $20
         fcb   $70 p
         fcb   $75 u
         fcb   $74 t
         fcb   $73 s
         fcb   $20
         fcb   $63 c
         fcb   $6F o
         fcb   $6D m
         fcb   $70 p
         fcb   $75 u
         fcb   $74 t
         fcb   $65 e
         fcb   $72 r
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $53 S
         fcb   $6C l
         fcb   $65 e
         fcb   $65 e
         fcb   $70 p
         fcb   $20
         fcb   $75 u
         fcb   $6E n
         fcb   $74 t
         fcb   $69 i
         fcb   $6C l
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $61 a
         fcb   $6E n
         fcb   $79 y
         fcb   $20
         fcb   $6B k
         fcb   $65 e
         fcb   $79 y
         fcb   $20
         fcb   $69 i
         fcb   $73 s
         fcb   $20
         fcb   $73 s
         fcb   $74 t
         fcb   $72 r
         fcb   $75 u
         fcb   $63 c
         fcb   $6B k
         fcb   $00

         fcc   "System:"
         fcb   $0D
         fcb   $0A
         fcb   $43 C
         fcb   $20
         fcb   $20
         fcb   $43 C
         fcb   $68 h
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $20
         fcb   $74 t
         fcb   $68 h
         fcb   $65 e
         fcb   $20
         fcb   $63 c
         fcb   $75 u
         fcb   $72 r
         fcb   $72 r
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $20
         fcb   $64 d
         fcb   $69 i
         fcb   $72 r
         fcb   $65 e
         fcb   $63 c
         fcb   $74 t
         fcb   $6F o
         fcb   $72 r
         fcb   $79 y
         fcb   $0D
         fcb   $4C L
         fcb   $20
         fcb   $20
         fcb   $4C L
         fcb   $6F o
         fcb   $61 a
         fcb   $64 d
         fcb   $20
         fcb   $77 w
         fcb   $6F o
         fcb   $72 r
         fcb   $6B k
         fcb   $73 s
         fcb   $68 h
         fcb   $65 e
         fcb   $65 e
         fcb   $74 t
         fcb   $20
         fcb   $66 f
         fcb   $72 r
         fcb   $6F o
         fcb   $6D m
         fcb   $20
         fcb   $64 d
         fcb   $69 i
         fcb   $73 s
         fcb   $6B k
         fcb   $2D -
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $6F o
         fcb   $76 v
         fcb   $65 e
         fcb   $72 r
         fcb   $6C l
         fcb   $61 a
         fcb   $79 y
         fcb   $73 s
         fcb   $20
         fcb   $63 c
         fcb   $75 u
         fcb   $72 r
         fcb   $72 r
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $20
         fcb   $73 s
         fcb   $68 h
         fcb   $65 e
         fcb   $65 e
         fcb   $74 t
         fcb   $0D
         fcb   $53 S
         fcb   $20
         fcb   $20
         fcb   $53 S
         fcb   $61 a
         fcb   $76 v
         fcb   $65 e
         fcb   $20
         fcb   $63 c
         fcb   $75 u
         fcb   $72 r
         fcb   $72 r
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $20
         fcb   $73 s
         fcb   $68 h
         fcb   $65 e
         fcb   $65 e
         fcb   $74 t
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $64 d
         fcb   $69 i
         fcb   $73 s
         fcb   $6B k
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $53 S
         fcb   $61 a
         fcb   $76 v
         fcb   $65 e
         fcb   $20
         fcb   $61 a
         fcb   $6E n
         fcb   $64 d
         fcb   $20
         fcb   $4C L
         fcb   $6F o
         fcb   $61 a
         fcb   $64 d
         fcb   $20
         fcb   $62 b
         fcb   $6F o
         fcb   $74 t
         fcb   $68 h
         fcb   $20
         fcb   $64 d
         fcb   $65 e
         fcb   $66 f
         fcb   $61 a
         fcb   $75 u
         fcb   $6C l
         fcb   $74 t
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $2E .
         fcb   $63 c
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $20
         fcb   $77 w
         fcb   $6F o
         fcb   $72 r
         fcb   $6B k
         fcb   $20
         fcb   $64 d
         fcb   $69 i
         fcb   $72 r
         fcb   $65 e
         fcb   $63 c
         fcb   $74 t
         fcb   $6F o
         fcb   $72 r
         fcb   $79 y
         fcb   $0D
         fcb   $58 X
         fcb   $20
         fcb   $20
         fcb   $65 e
         fcb   $58 X
         fcb   $65 e
         fcb   $63 c
         fcb   $75 u
         fcb   $74 t
         fcb   $65 e
         fcb   $20
         fcb   $4F O
         fcb   $53 S
         fcb   $2D -
         fcb   $39 9
         fcb   $20
         fcb   $63 c
         fcb   $6F o
         fcb   $6D m
         fcb   $6D m
         fcb   $61 a
         fcb   $6E n
         fcb   $64 d
         fcb   $0D
         fcb   $23 #
         fcb   $20
         fcb   $20
         fcb   $64 d
         fcb   $61 a
         fcb   $74 t
         fcb   $61 a
         fcb   $20
         fcb   $66 f
         fcb   $69 i
         fcb   $6C l
         fcb   $65 e
         fcb   $20
         fcb   $73 s
         fcb   $61 a
         fcb   $76 v
         fcb   $65 e
         fcb   $2F /
         fcb   $6C l
         fcb   $6F o
         fcb   $61 a
         fcb   $64 d
         fcb   $2D -
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $66 f
         fcb   $6F o
         fcb   $72 r
         fcb   $20
         fcb   $64 d
         fcb   $61 a
         fcb   $74 t
         fcb   $61 a
         fcb   $20
         fcb   $65 e
         fcb   $78 x
         fcb   $63 c
         fcb   $68 h
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $62 b
         fcb   $6F o
         fcb   $74 t
         fcb   $68 h
         fcb   $20
         fcb   $64 d
         fcb   $65 e
         fcb   $66 f
         fcb   $61 a
         fcb   $75 u
         fcb   $6C l
         fcb   $74 t
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $74 t
         fcb   $68 h
         fcb   $65 e
         fcb   $20
         fcb   $63 c
         fcb   $75 u
         fcb   $72 r
         fcb   $2D -
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $72 r
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $20
         fcb   $77 w
         fcb   $6F o
         fcb   $72 r
         fcb   $6B k
         fcb   $69 i
         fcb   $6E n
         fcb   $67 g
         fcb   $20
         fcb   $64 d
         fcb   $69 i
         fcb   $72 r
         fcb   $65 e
         fcb   $63 c
         fcb   $74 t
         fcb   $6F o
         fcb   $72 r
         fcb   $79 y
         fcb   $00

         fcc   "Save data:"
         fcb   $0D
         fcb   $0A
         fcb   $4C L
         fcb   $20
         fcb   $20
         fcb   $4C L
         fcb   $6F o
         fcb   $61 a
         fcb   $64 d
         fcb   $20
         fcb   $6C l
         fcb   $61 a
         fcb   $62 b
         fcb   $65 e
         fcb   $6C l
         fcb   $73 s
         fcb   $20
         fcb   $61 a
         fcb   $6E n
         fcb   $64 d
         fcb   $20
         fcb   $43 C
         fcb   $41 A
         fcb   $4C L
         fcb   $43 C
         fcb   $55 U
         fcb   $4C L
         fcb   $41 A
         fcb   $54 T
         fcb   $45 E
         fcb   $44 D
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $56 V
         fcb   $61 a
         fcb   $6C l
         fcb   $75 u
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $66 f
         fcb   $72 r
         fcb   $6F o
         fcb   $6D m
         fcb   $20
         fcb   $64 d
         fcb   $69 i
         fcb   $73 s
         fcb   $6B k
         fcb   $0D
         fcb   $0A
         fcb   $53 S
         fcb   $20
         fcb   $20
         fcb   $53 S
         fcb   $61 a
         fcb   $76 v
         fcb   $65 e
         fcb   $20
         fcb   $6C l
         fcb   $61 a
         fcb   $62 b
         fcb   $65 e
         fcb   $6C l
         fcb   $73 s
         fcb   $20
         fcb   $61 a
         fcb   $6E n
         fcb   $64 d
         fcb   $20
         fcb   $43 C
         fcb   $41 A
         fcb   $4C L
         fcb   $43 C
         fcb   $55 U
         fcb   $4C L
         fcb   $41 A
         fcb   $54 T
         fcb   $45 E
         fcb   $44 D
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $56 V
         fcb   $61 a
         fcb   $6C l
         fcb   $75 u
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $64 d
         fcb   $69 i
         fcb   $73 s
         fcb   $6B k
         fcb   $00

         fcc   "Titles:"
         fcb   $0D
         fcb   $0A
         fcb   $42 B
         fcb   $20
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $74 t
         fcb   $20
         fcb   $75 u
         fcb   $70 p
         fcb   $20
         fcb   $42 B
         fcb   $6F o
         fcb   $74 t
         fcb   $68 h
         fcb   $20
         fcb   $68 h
         fcb   $6F o
         fcb   $72 r
         fcb   $69 i
         fcb   $7A z
         fcb   $6F o
         fcb   $6E n
         fcb   $74 t
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $61 a
         fcb   $6E n
         fcb   $64 d
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $76 v
         fcb   $65 e
         fcb   $72 r
         fcb   $74 t
         fcb   $69 i
         fcb   $63 c
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $74 t
         fcb   $69 i
         fcb   $74 t
         fcb   $6C l
         fcb   $65 e
         fcb   $73 s
         fcb   $0D
         fcb   $48 H
         fcb   $20
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $74 t
         fcb   $20
         fcb   $75 u
         fcb   $70 p
         fcb   $20
         fcb   $72 r
         fcb   $6F o
         fcb   $77 w
         fcb   $28 (
         fcb   $73 s
         fcb   $29 )
         fcb   $20
         fcb   $61 a
         fcb   $62 b
         fcb   $6F o
         fcb   $76 v
         fcb   $65 e
         fcb   $20
         fcb   $63 c
         fcb   $75 u
         fcb   $72 r
         fcb   $73 s
         fcb   $6F o
         fcb   $72 r
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $61 a
         fcb   $73 s
         fcb   $20
         fcb   $48 H
         fcb   $6F o
         fcb   $72 r
         fcb   $69 i
         fcb   $7A z
         fcb   $6F o
         fcb   $6E n
         fcb   $74 t
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $74 t
         fcb   $69 i
         fcb   $74 t
         fcb   $6C l
         fcb   $65 e
         fcb   $20
         fcb   $61 a
         fcb   $72 r
         fcb   $65 e
         fcb   $61 a
         fcb   $0D
         fcb   $4E N
         fcb   $20
         fcb   $20
         fcb   $4E N
         fcb   $6F o
         fcb   $20
         fcb   $74 t
         fcb   $69 i
         fcb   $74 t
         fcb   $6C l
         fcb   $65 e
         fcb   $73 s
         fcb   $0D
         fcb   $56 V
         fcb   $20
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $74 t
         fcb   $20
         fcb   $75 u
         fcb   $70 p
         fcb   $20
         fcb   $63 c
         fcb   $6F o
         fcb   $6C l
         fcb   $75 u
         fcb   $6D m
         fcb   $6E n
         fcb   $28 (
         fcb   $73 s
         fcb   $29 )
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $6C l
         fcb   $65 e
         fcb   $66 f
         fcb   $74 t
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $63 c
         fcb   $75 u
         fcb   $72 r
         fcb   $73 s
         fcb   $6F o
         fcb   $72 r
         fcb   $20
         fcb   $61 a
         fcb   $73 s
         fcb   $20
         fcb   $56 V
         fcb   $65 e
         fcb   $72 r
         fcb   $74 t
         fcb   $69 i
         fcb   $63 c
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $74 t
         fcb   $69 i
         fcb   $74 t
         fcb   $6C l
         fcb   $65 e
         fcb   $28 (
         fcb   $73 s
         fcb   $29 )
         fcb   $00

         fcc   "Windows:"
         fcb   $0D
         fcb   $0A
         fcb   $44 D
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $67 g
         fcb   $67 g
         fcb   $6C l
         fcb   $65 e
         fcb   $20
         fcb   $76 v
         fcb   $61 a
         fcb   $6C l
         fcb   $75 u
         fcb   $65 e
         fcb   $2F /
         fcb   $66 f
         fcb   $6F o
         fcb   $72 r
         fcb   $6D m
         fcb   $75 u
         fcb   $6C l
         fcb   $61 a
         fcb   $20
         fcb   $44 D
         fcb   $69 i
         fcb   $73 s
         fcb   $70 p
         fcb   $6C l
         fcb   $61 a
         fcb   $79 y
         fcb   $0D
         fcb   $46 F
         fcb   $20
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $74 t
         fcb   $20
         fcb   $64 d
         fcb   $65 e
         fcb   $66 f
         fcb   $61 a
         fcb   $75 u
         fcb   $6C l
         fcb   $74 t
         fcb   $20
         fcb   $46 F
         fcb   $6F o
         fcb   $72 r
         fcb   $6D m
         fcb   $61 a
         fcb   $74 t
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $61 a
         fcb   $6C l
         fcb   $6C l
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $63 c
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $73 s
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $20
         fcb   $63 c
         fcb   $75 u
         fcb   $72 r
         fcb   $72 r
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $20
         fcb   $77 w
         fcb   $69 i
         fcb   $6E n
         fcb   $64 d
         fcb   $6F o
         fcb   $77 w
         fcb   $0D
         fcb   $48 H
         fcb   $20
         fcb   $20
         fcb   $64 d
         fcb   $69 i
         fcb   $76 v
         fcb   $69 i
         fcb   $64 d
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $73 s
         fcb   $63 c
         fcb   $72 r
         fcb   $65 e
         fcb   $65 e
         fcb   $6E n
         fcb   $20
         fcb   $48 H
         fcb   $6F o
         fcb   $72 r
         fcb   $69 i
         fcb   $7A z
         fcb   $6F o
         fcb   $6E n
         fcb   $74 t
         fcb   $61 a
         fcb   $6C l
         fcb   $6C l
         fcb   $79 y
         fcb   $0D
         fcb   $4E N
         fcb   $20
         fcb   $20
         fcb   $4E N
         fcb   $6F o
         fcb   $20
         fcb   $64 d
         fcb   $69 i
         fcb   $76 v
         fcb   $69 i
         fcb   $73 s
         fcb   $69 i
         fcb   $6F o
         fcb   $6E n
         fcb   $20
         fcb   $2D -
         fcb   $20
         fcb   $72 r
         fcb   $65 e
         fcb   $74 t
         fcb   $75 u
         fcb   $72 r
         fcb   $6E n
         fcb   $73 s
         fcb   $20
         fcb   $64 d
         fcb   $69 i
         fcb   $73 s
         fcb   $2D -
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $70 p
         fcb   $6C l
         fcb   $61 a
         fcb   $79 y
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $73 s
         fcb   $69 i
         fcb   $6E n
         fcb   $67 g
         fcb   $6C l
         fcb   $65 e
         fcb   $20
         fcb   $77 w
         fcb   $69 i
         fcb   $6E n
         fcb   $64 d
         fcb   $6F o
         fcb   $77 w
         fcb   $0D
         fcb   $53 S
         fcb   $20
         fcb   $20
         fcb   $53 S
         fcb   $79 y
         fcb   $6E n
         fcb   $63 c
         fcb   $68 h
         fcb   $72 r
         fcb   $6F o
         fcb   $6E n
         fcb   $69 i
         fcb   $7A z
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $6D m
         fcb   $6F o
         fcb   $74 t
         fcb   $69 i
         fcb   $6F o
         fcb   $6E n
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $77 w
         fcb   $6F o
         fcb   $20
         fcb   $77 w
         fcb   $69 i
         fcb   $6E n
         fcb   $64 d
         fcb   $6F o
         fcb   $77 w
         fcb   $73 s
         fcb   $0D
         fcb   $55 U
         fcb   $20
         fcb   $20
         fcb   $55 U
         fcb   $6E n
         fcb   $73 s
         fcb   $79 y
         fcb   $6E n
         fcb   $63 c
         fcb   $68 h
         fcb   $72 r
         fcb   $6F o
         fcb   $6E n
         fcb   $69 i
         fcb   $7A z
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $6D m
         fcb   $6F o
         fcb   $74 t
         fcb   $69 i
         fcb   $6F o
         fcb   $6E n
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $77 w
         fcb   $6F o
         fcb   $20
         fcb   $77 w
         fcb   $69 i
         fcb   $6E n
         fcb   $64 d
         fcb   $6F o
         fcb   $77 w
         fcb   $73 s
         fcb   $20
         fcb   $28 (
         fcb   $64 d
         fcb   $65 e
         fcb   $66 f
         fcb   $61 a
         fcb   $75 u
         fcb   $6C l
         fcb   $74 t
         fcb   $29 )
         fcb   $0D
         fcb   $56 V
         fcb   $20
         fcb   $20
         fcb   $64 d
         fcb   $69 i
         fcb   $76 v
         fcb   $69 i
         fcb   $64 d
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $73 s
         fcb   $63 c
         fcb   $72 r
         fcb   $65 e
         fcb   $65 e
         fcb   $6E n
         fcb   $20
         fcb   $56 V
         fcb   $65 e
         fcb   $72 r
         fcb   $74 t
         fcb   $69 i
         fcb   $63 c
         fcb   $61 a
         fcb   $6C l
         fcb   $6C l
         fcb   $79 y
         fcb   $00

         fcc   "Set default format of window:"
         fcb   $0D
         fcb   $0A
         fcb   $43 C
         fcb   $20
         fcb   $20
         fcb   $43 C
         fcb   $6F o
         fcb   $6E n
         fcb   $74 t
         fcb   $69 i
         fcb   $6E n
         fcb   $75 u
         fcb   $6F o
         fcb   $75 u
         fcb   $73 s
         fcb   $20
         fcb   $2D -
         fcb   $20
         fcb   $63 c
         fcb   $68 h
         fcb   $61 a
         fcb   $72 r
         fcb   $61 a
         fcb   $63 c
         fcb   $74 t
         fcb   $65 e
         fcb   $72 r
         fcb   $73 s
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $72 r
         fcb   $65 e
         fcb   $70 p
         fcb   $65 e
         fcb   $61 a
         fcb   $74 t
         fcb   $65 e
         fcb   $64 d
         fcb   $20
         fcb   $74 t
         fcb   $68 h
         fcb   $72 r
         fcb   $6F o
         fcb   $75 u
         fcb   $67 g
         fcb   $68 h
         fcb   $6F o
         fcb   $75 u
         fcb   $74 t
         fcb   $20
         fcb   $63 c
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $0D
         fcb   $44 D
         fcb   $20
         fcb   $20
         fcb   $44 D
         fcb   $65 e
         fcb   $66 f
         fcb   $61 a
         fcb   $75 u
         fcb   $6C l
         fcb   $74 t
         fcb   $20
         fcb   $2D -
         fcb   $20
         fcb   $75 u
         fcb   $73 s
         fcb   $65 e
         fcb   $20
         fcb   $67 g
         fcb   $65 e
         fcb   $6E n
         fcb   $65 e
         fcb   $72 r
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $66 f
         fcb   $6F o
         fcb   $72 r
         fcb   $6D m
         fcb   $61 a
         fcb   $74 t
         fcb   $0D
         fcb   $47 G
         fcb   $20
         fcb   $20
         fcb   $47 G
         fcb   $65 e
         fcb   $6E n
         fcb   $65 e
         fcb   $72 r
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $2D -
         fcb   $20
         fcb   $66 f
         fcb   $72 r
         fcb   $65 e
         fcb   $65 e
         fcb   $2D -
         fcb   $66 f
         fcb   $6F o
         fcb   $72 r
         fcb   $6D m
         fcb   $61 a
         fcb   $74 t
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $28 (
         fcb   $6C l
         fcb   $61 a
         fcb   $62 b
         fcb   $65 e
         fcb   $6C l
         fcb   $73 s
         fcb   $20
         fcb   $6C l
         fcb   $65 e
         fcb   $66 f
         fcb   $74 t
         fcb   $2C ,
         fcb   $20
         fcb   $6E n
         fcb   $75 u
         fcb   $6D m
         fcb   $62 b
         fcb   $65 e
         fcb   $72 r
         fcb   $73 s
         fcb   $20
         fcb   $72 r
         fcb   $69 i
         fcb   $67 g
         fcb   $68 h
         fcb   $74 t
         fcb   $29 )
         fcb   $0D
         fcb   $49 I
         fcb   $20
         fcb   $20
         fcb   $49 I
         fcb   $6E n
         fcb   $74 t
         fcb   $65 e
         fcb   $67 g
         fcb   $65 e
         fcb   $72 r
         fcb   $20
         fcb   $2D -
         fcb   $20
         fcb   $72 r
         fcb   $6F o
         fcb   $75 u
         fcb   $6E n
         fcb   $64 d
         fcb   $73 s
         fcb   $20
         fcb   $44 D
         fcb   $49 I
         fcb   $53 S
         fcb   $50 P
         fcb   $4C L
         fcb   $41 A
         fcb   $59 Y
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $6E n
         fcb   $65 e
         fcb   $61 a
         fcb   $72 r
         fcb   $65 e
         fcb   $73 s
         fcb   $74 t
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $74 t
         fcb   $65 e
         fcb   $67 g
         fcb   $65 e
         fcb   $72 r
         fcb   $0D
         fcb   $4C L
         fcb   $20
         fcb   $20
         fcb   $4C L
         fcb   $65 e
         fcb   $66 f
         fcb   $74 t
         fcb   $20
         fcb   $6A j
         fcb   $75 u
         fcb   $73 s
         fcb   $74 t
         fcb   $69 i
         fcb   $66 f
         fcb   $79 y
         fcb   $20
         fcb   $2D -
         fcb   $20
         fcb   $66 f
         fcb   $6F o
         fcb   $72 r
         fcb   $63 c
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $6E n
         fcb   $75 u
         fcb   $6D m
         fcb   $62 b
         fcb   $65 e
         fcb   $72 r
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $6C l
         fcb   $65 e
         fcb   $66 f
         fcb   $74 t
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $63 c
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $0D
         fcb   $0A
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $48 H
         fcb   $69 i
         fcb   $74 t
         fcb   $20
         fcb   $61 a
         fcb   $6E n
         fcb   $79 y
         fcb   $20
         fcb   $6B k
         fcb   $65 e
         fcb   $79 y
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $65 e
         fcb   $20
         fcb   $70 p
         fcb   $61 a
         fcb   $67 g
         fcb   $65 e
         fcb   $20
         fcb   $32 2
         fcb   $11
         fcb   $50 P
         fcb   $20
         fcb   $20
         fcb   $50 P
         fcb   $6C l
         fcb   $6F o
         fcb   $74 t
         fcb   $20
         fcb   $2D -
         fcb   $20
         fcb   $75 u
         fcb   $73 s
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $63 c
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $27 '
         fcb   $73 s
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $74 t
         fcb   $65 e
         fcb   $67 g
         fcb   $65 e
         fcb   $72 r
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $76 v
         fcb   $61 a
         fcb   $6C l
         fcb   $75 u
         fcb   $65 e
         fcb   $20
         fcb   $61 a
         fcb   $73 s
         fcb   $20
         fcb   $6E n
         fcb   $75 u
         fcb   $6D m
         fcb   $62 b
         fcb   $65 e
         fcb   $72 r
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $67 g
         fcb   $72 r
         fcb   $61 a
         fcb   $70 p
         fcb   $68 h
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $63 c
         fcb   $68 h
         fcb   $61 a
         fcb   $72 r
         fcb   $61 a
         fcb   $63 c
         fcb   $74 t
         fcb   $65 e
         fcb   $72 r
         fcb   $73 s
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $70 p
         fcb   $72 r
         fcb   $69 i
         fcb   $6E n
         fcb   $74 t
         fcb   $0D
         fcb   $52 R
         fcb   $20
         fcb   $20
         fcb   $52 R
         fcb   $69 i
         fcb   $67 g
         fcb   $68 h
         fcb   $74 t
         fcb   $20
         fcb   $6A j
         fcb   $75 u
         fcb   $73 s
         fcb   $74 t
         fcb   $69 i
         fcb   $66 f
         fcb   $79 y
         fcb   $20
         fcb   $2D -
         fcb   $20
         fcb   $66 f
         fcb   $6F o
         fcb   $72 r
         fcb   $63 c
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $6C l
         fcb   $61 a
         fcb   $62 b
         fcb   $65 e
         fcb   $6C l
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $72 r
         fcb   $69 i
         fcb   $67 g
         fcb   $68 h
         fcb   $74 t
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $63 c
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $0D
         fcb   $24 $
         fcb   $20
         fcb   $20
         fcb   $44 D
         fcb   $6F o
         fcb   $6C l
         fcb   $6C l
         fcb   $61 a
         fcb   $72 r
         fcb   $20
         fcb   $2D -
         fcb   $20
         fcb   $72 r
         fcb   $6F o
         fcb   $75 u
         fcb   $6E n
         fcb   $64 d
         fcb   $73 s
         fcb   $20
         fcb   $44 D
         fcb   $49 I
         fcb   $53 S
         fcb   $50 P
         fcb   $4C L
         fcb   $41 A
         fcb   $59 Y
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $6E n
         fcb   $65 e
         fcb   $61 a
         fcb   $72 r
         fcb   $65 e
         fcb   $73 s
         fcb   $74 t
         fcb   $20
         fcb   $63 c
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $00
         
         fcc   "Printer attributes:"
         fcb   $0D
         fcb   $0A
         fcb   $42 B
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $67 g
         fcb   $67 g
         fcb   $6C l
         fcb   $65 e
         fcb   $20
         fcb   $42 B
         fcb   $6F o
         fcb   $72 r
         fcb   $64 d
         fcb   $65 e
         fcb   $72 r
         fcb   $20
         fcb   $66 f
         fcb   $6C l
         fcb   $61 a
         fcb   $67 g
         fcb   $20
         fcb   $6F o
         fcb   $6E n
         fcb   $2F /
         fcb   $6F o
         fcb   $66 f
         fcb   $66 f
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $28 (
         fcb   $64 d
         fcb   $65 e
         fcb   $66 f
         fcb   $61 a
         fcb   $75 u
         fcb   $6C l
         fcb   $74 t
         fcb   $73 s
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $66 f
         fcb   $29 )
         fcb   $0D
         fcb   $43 C
         fcb   $20
         fcb   $20
         fcb   $43 C
         fcb   $6C l
         fcb   $65 e
         fcb   $61 a
         fcb   $72 r
         fcb   $73 s
         fcb   $20
         fcb   $74 t
         fcb   $68 h
         fcb   $65 e
         fcb   $20
         fcb   $70 p
         fcb   $72 r
         fcb   $69 i
         fcb   $6E n
         fcb   $74 t
         fcb   $65 e
         fcb   $72 r
         fcb   $20
         fcb   $66 f
         fcb   $69 i
         fcb   $6C l
         fcb   $65 e
         fcb   $20
         fcb   $6E n
         fcb   $61 a
         fcb   $6D m
         fcb   $65 e
         fcb   $0D
         fcb   $4C L
         fcb   $20
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $74 t
         fcb   $20
         fcb   $4C L
         fcb   $65 e
         fcb   $6E n
         fcb   $67 g
         fcb   $74 t
         fcb   $68 h
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $70 p
         fcb   $61 a
         fcb   $67 g
         fcb   $65 e
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $28 (
         fcb   $64 d
         fcb   $65 e
         fcb   $66 f
         fcb   $61 a
         fcb   $75 u
         fcb   $6C l
         fcb   $74 t
         fcb   $73 s
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $35 5
         fcb   $38 8
         fcb   $20
         fcb   $6C l
         fcb   $69 i
         fcb   $6E n
         fcb   $65 e
         fcb   $73 s
         fcb   $29 )
         fcb   $0D
         fcb   $50 P
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $67 g
         fcb   $67 g
         fcb   $6C l
         fcb   $65 e
         fcb   $20
         fcb   $50 P
         fcb   $61 a
         fcb   $67 g
         fcb   $69 i
         fcb   $6E n
         fcb   $61 a
         fcb   $74 t
         fcb   $69 i
         fcb   $6F o
         fcb   $6E n
         fcb   $20
         fcb   $6F o
         fcb   $6E n
         fcb   $2F /
         fcb   $6F o
         fcb   $66 f
         fcb   $66 f
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $28 (
         fcb   $64 d
         fcb   $65 e
         fcb   $66 f
         fcb   $61 a
         fcb   $75 u
         fcb   $6C l
         fcb   $74 t
         fcb   $73 s
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $6F o
         fcb   $6E n
         fcb   $29 )
         fcb   $0D
         fcb   $53 S
         fcb   $20
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $74 t
         fcb   $20
         fcb   $74 t
         fcb   $68 h
         fcb   $65 e
         fcb   $20
         fcb   $53 S
         fcb   $70 p
         fcb   $61 a
         fcb   $63 c
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $62 b
         fcb   $65 e
         fcb   $74 t
         fcb   $77 w
         fcb   $65 e
         fcb   $65 e
         fcb   $6E n
         fcb   $20
         fcb   $6C l
         fcb   $69 i
         fcb   $6E n
         fcb   $65 e
         fcb   $73 s
         fcb   $0D
         fcb   $57 W
         fcb   $20
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $74 t
         fcb   $20
         fcb   $57 W
         fcb   $69 i
         fcb   $64 d
         fcb   $74 t
         fcb   $68 h
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $70 p
         fcb   $61 a
         fcb   $67 g
         fcb   $65 e
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $28 (
         fcb   $64 d
         fcb   $65 e
         fcb   $66 f
         fcb   $61 a
         fcb   $75 u
         fcb   $6C l
         fcb   $74 t
         fcb   $73 s
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $38 8
         fcb   $30 0
         fcb   $20
         fcb   $63 c
         fcb   $68 h
         fcb   $61 a
         fcb   $72 r
         fcb   $61 a
         fcb   $63 c
         fcb   $74 t
         fcb   $65 e
         fcb   $72 r
         fcb   $73 s
         fcb   $29 )
         fcb   $00

         fcc   "Width:"
         fcb   $0D
         fcb   $0A
         fcb   $43 C
         fcb   $20
         fcb   $20
         fcb   $63 c
         fcb   $68 h
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $77 w
         fcb   $69 i
         fcb   $64 d
         fcb   $74 t
         fcb   $68 h
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $63 c
         fcb   $75 u
         fcb   $72 r
         fcb   $72 r
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $20
         fcb   $43 C
         fcb   $6F o
         fcb   $6C l
         fcb   $75 u
         fcb   $6D m
         fcb   $6E n
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $28 (
         fcb   $64 d
         fcb   $65 e
         fcb   $66 f
         fcb   $61 a
         fcb   $75 u
         fcb   $6C l
         fcb   $74 t
         fcb   $73 s
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $57 W
         fcb   $69 i
         fcb   $6E n
         fcb   $64 d
         fcb   $6F o
         fcb   $77 w
         fcb   $20
         fcb   $76 v
         fcb   $61 a
         fcb   $6C l
         fcb   $75 u
         fcb   $65 e
         fcb   $29 )
         fcb   $0D
         fcb   $0A
         fcb   $57 W
         fcb   $20
         fcb   $20
         fcb   $63 c
         fcb   $68 h
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $64 d
         fcb   $65 e
         fcb   $66 f
         fcb   $61 a
         fcb   $75 u
         fcb   $6C l
         fcb   $74 t
         fcb   $20
         fcb   $77 w
         fcb   $69 i
         fcb   $64 d
         fcb   $74 t
         fcb   $68 h
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $61 a
         fcb   $6C l
         fcb   $6C l
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $63 c
         fcb   $6F o
         fcb   $6C l
         fcb   $75 u
         fcb   $6D m
         fcb   $6E n
         fcb   $73 s
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $20
         fcb   $63 c
         fcb   $75 u
         fcb   $72 r
         fcb   $72 r
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $20
         fcb   $57 W
         fcb   $69 i
         fcb   $6E n
         fcb   $64 d
         fcb   $6F o
         fcb   $77 w
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $28 (
         fcb   $64 d
         fcb   $65 e
         fcb   $66 f
         fcb   $61 a
         fcb   $75 u
         fcb   $6C l
         fcb   $74 t
         fcb   $73 s
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $39 9
         fcb   $20
         fcb   $63 c
         fcb   $68 h
         fcb   $61 a
         fcb   $72 r
         fcb   $61 a
         fcb   $63 c
         fcb   $74 t
         fcb   $65 e
         fcb   $72 r
         fcb   $73 s
         fcb   $29 )
         fcb   $00

         fcc   "Move column/row:"
         fcb   $0D
         fcb   $0A
         fcb   $41 A
         fcb   $20
         fcb   $20
         fcb   $73 s
         fcb   $6F o
         fcb   $72 r
         fcb   $74 t
         fcb   $20
         fcb   $63 c
         fcb   $6F o
         fcb   $6C l
         fcb   $75 u
         fcb   $6D m
         fcb   $6E n
         fcb   $73 s
         fcb   $2F /
         fcb   $72 r
         fcb   $6F o
         fcb   $77 w
         fcb   $73 s
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $20
         fcb   $72 r
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $20
         fcb   $41 A
         fcb   $73 s
         fcb   $63 c
         fcb   $65 e
         fcb   $6E n
         fcb   $64 d
         fcb   $69 i
         fcb   $6E n
         fcb   $67 g
         fcb   $20
         fcb   $6F o
         fcb   $72 r
         fcb   $64 d
         fcb   $65 e
         fcb   $72 r
         fcb   $0D
         fcb   $44 D
         fcb   $20
         fcb   $20
         fcb   $73 s
         fcb   $6F o
         fcb   $72 r
         fcb   $74 t
         fcb   $20
         fcb   $63 c
         fcb   $6F o
         fcb   $6C l
         fcb   $75 u
         fcb   $6D m
         fcb   $6E n
         fcb   $73 s
         fcb   $2F /
         fcb   $72 r
         fcb   $6F o
         fcb   $77 w
         fcb   $73 s
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $20
         fcb   $72 r
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $20
         fcb   $44 D
         fcb   $65 e
         fcb   $73 s
         fcb   $63 c
         fcb   $65 e
         fcb   $6E n
         fcb   $64 d
         fcb   $69 i
         fcb   $6E n
         fcb   $67 g
         fcb   $20
         fcb   $6F o
         fcb   $72 r
         fcb   $64 d
         fcb   $65 e
         fcb   $72 r
         fcb   $0D
         fcb   $4D M
         fcb   $20
         fcb   $20
         fcb   $4D M
         fcb   $61 a
         fcb   $6E n
         fcb   $75 u
         fcb   $61 a
         fcb   $6C l
         fcb   $6C l
         fcb   $79 y
         fcb   $20
         fcb   $6D m
         fcb   $6F o
         fcb   $76 v
         fcb   $65 e
         fcb   $20
         fcb   $63 c
         fcb   $6F o
         fcb   $6C l
         fcb   $75 u
         fcb   $6D m
         fcb   $6E n
         fcb   $2F /
         fcb   $72 r
         fcb   $6F o
         fcb   $77 w
         fcb   $00

         fcc   "Order:"
         fcb   $0D
         fcb   $0A
         fcb   $43 C
         fcb   $20
         fcb   $20
         fcb   $6C l
         fcb   $6F o
         fcb   $61 a
         fcb   $64 d
         fcb   $73 s
         fcb   $2F /
         fcb   $73 s
         fcb   $61 a
         fcb   $76 v
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $64 d
         fcb   $61 a
         fcb   $74 t
         fcb   $61 a
         fcb   $20
         fcb   $62 b
         fcb   $79 y
         fcb   $20
         fcb   $43 C
         fcb   $6F o
         fcb   $6C l
         fcb   $75 u
         fcb   $6D m
         fcb   $6E n
         fcb   $0D
         fcb   $44 D
         fcb   $20
         fcb   $20
         fcb   $6C l
         fcb   $6F o
         fcb   $61 a
         fcb   $64 d
         fcb   $73 s
         fcb   $2F /
         fcb   $73 s
         fcb   $61 a
         fcb   $76 v
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $64 d
         fcb   $61 a
         fcb   $74 t
         fcb   $61 a
         fcb   $20
         fcb   $62 b
         fcb   $79 y
         fcb   $20
         fcb   $44 D
         fcb   $65 e
         fcb   $66 f
         fcb   $61 a
         fcb   $75 u
         fcb   $6C l
         fcb   $74 t
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $6F o
         fcb   $72 r
         fcb   $64 d
         fcb   $65 e
         fcb   $72 r
         fcb   $0D
         fcb   $52 R
         fcb   $20
         fcb   $20
         fcb   $6C l
         fcb   $6F o
         fcb   $61 a
         fcb   $64 d
         fcb   $73 s
         fcb   $2F /
         fcb   $73 s
         fcb   $61 a
         fcb   $76 v
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $64 d
         fcb   $61 a
         fcb   $74 t
         fcb   $61 a
         fcb   $20
         fcb   $62 b
         fcb   $79 y
         fcb   $20
         fcb   $52 R
         fcb   $6F o
         fcb   $77 w
         fcb   $73 s
         fcb   $00
         fcc   "Trigonometric:"
         fcb   $0D
         fcc   "@SIN    @ASIN     @PI (3.14...)"
         fcb   $0D
         fcc   "@COS    @ACOS "
         fcb   $0D
         fcc   "@TAN    @ATAN "
         fcb   $0D
         fcb   $0A
         fcb   $4C L
         fcb   $6F o
         fcb   $67 g
         fcb   $61 a
         fcb   $72 r
         fcb   $69 i
         fcb   $74 t
         fcb   $68 h
         fcb   $6D m
         fcb   $69 i
         fcb   $63 c
         fcb   $3A :
         fcb   $0D
         fcb   $40 @
         fcb   $4C L
         fcb   $4E N
         fcb   $28 (
         fcb   $78 x
         fcb   $29 )
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $6C l
         fcb   $6F o
         fcb   $67 g
         fcb   $61 a
         fcb   $72 r
         fcb   $69 i
         fcb   $74 t
         fcb   $68 h
         fcb   $6D m
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $78 x
         fcb   $2C ,
         fcb   $20
         fcb   $62 b
         fcb   $61 a
         fcb   $73 s
         fcb   $65 e
         fcb   $20
         fcb   $65 e
         fcb   $0D
         fcb   $40 @
         fcb   $4C L
         fcb   $4F O
         fcb   $47 G
         fcb   $28 (
         fcb   $78 x
         fcb   $29 )
         fcb   $20
         fcb   $20
         fcb   $6C l
         fcb   $6F o
         fcb   $67 g
         fcb   $2E .
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $78 x
         fcb   $2C ,
         fcb   $20
         fcb   $62 b
         fcb   $61 a
         fcb   $73 s
         fcb   $65 e
         fcb   $20
         fcb   $31 1
         fcb   $30 0
         fcb   $0D
         fcb   $40 @
         fcb   $45 E
         fcb   $58 X
         fcb   $50 P
         fcb   $28 (
         fcb   $78 x
         fcb   $29 )
         fcb   $20
         fcb   $20
         fcb   $65 e
         fcb   $20
         fcb   $72 r
         fcb   $61 a
         fcb   $69 i
         fcb   $73 s
         fcb   $65 e
         fcb   $64 d
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $78 x
         fcb   $20
         fcb   $70 p
         fcb   $6F o
         fcb   $77 w
         fcb   $65 e
         fcb   $72 r
         fcb   $0D
         fcb   $40 @
         fcb   $53 S
         fcb   $51 Q
         fcb   $52 R
         fcb   $54 T
         fcb   $28 (
         fcb   $78 x
         fcb   $29 )
         fcb   $20
         fcb   $73 s
         fcb   $71 q
         fcb   $75 u
         fcb   $61 a
         fcb   $72 r
         fcb   $65 e
         fcb   $20
         fcb   $72 r
         fcb   $6F o
         fcb   $6F o
         fcb   $74 t
         fcb   $20
         fcb   $78 x
         fcb   $0D
         fcb   $0A
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $48 H
         fcb   $69 i
         fcb   $74 t
         fcb   $20
         fcb   $61 a
         fcb   $6E n
         fcb   $79 y
         fcb   $20
         fcb   $6B k
         fcb   $65 e
         fcb   $79 y
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $65 e
         fcb   $20
         fcb   $70 p
         fcb   $61 a
         fcb   $67 g
         fcb   $65 e
         fcb   $20
         fcb   $32 2
         fcb   $0D
         fcb   $11
         fcb   $47 G
         fcb   $65 e
         fcb   $6E n
         fcb   $65 e
         fcb   $72 r
         fcb   $61 a
         fcb   $6C l
         fcb   $3A :
         fcb   $0D
         fcb   $40 @
         fcb   $41 A
         fcb   $42 B
         fcb   $53 S
         fcb   $28 (
         fcb   $78 x
         fcb   $29 )
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $61 a
         fcb   $62 b
         fcb   $73 s
         fcb   $6F o
         fcb   $6C l
         fcb   $75 u
         fcb   $74 t
         fcb   $65 e
         fcb   $20
         fcb   $76 v
         fcb   $61 a
         fcb   $6C l
         fcb   $75 u
         fcb   $65 e
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $78 x
         fcb   $0D
         fcb   $40 @
         fcb   $49 I
         fcb   $4E N
         fcb   $54 T
         fcb   $28 (
         fcb   $78 x
         fcb   $29 )
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $74 t
         fcb   $65 e
         fcb   $67 g
         fcb   $65 e
         fcb   $72 r
         fcb   $20
         fcb   $70 p
         fcb   $61 a
         fcb   $72 r
         fcb   $74 t
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $78 x
         fcb   $0D
         fcb   $40 @
         fcb   $52 R
         fcb   $4F O
         fcb   $55 U
         fcb   $4E N
         fcb   $44 D
         fcb   $28 (
         fcb   $64 d
         fcb   $2C ,
         fcb   $78 x
         fcb   $29 )
         fcb   $20
         fcb   $72 r
         fcb   $6F o
         fcb   $75 u
         fcb   $6E n
         fcb   $64 d
         fcb   $20
         fcb   $78 x
         fcb   $2C ,
         fcb   $20
         fcb   $6E n
         fcb   $65 e
         fcb   $61 a
         fcb   $72 r
         fcb   $65 e
         fcb   $73 s
         fcb   $74 t
         fcb   $20
         fcb   $64 d
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $28 (
         fcb   $64 d
         fcb   $20
         fcb   $6D m
         fcb   $75 u
         fcb   $73 s
         fcb   $74 t
         fcb   $20
         fcb   $62 b
         fcb   $65 e
         fcb   $20
         fcb   $65 e
         fcb   $76 v
         fcb   $65 e
         fcb   $6E n
         fcb   $20
         fcb   $70 p
         fcb   $6F o
         fcb   $77 w
         fcb   $65 e
         fcb   $72 r
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $31 1
         fcb   $30 0
         fcb   $29 )
         fcb   $0D
         fcb   $0A
         fcb   $53 S
         fcb   $65 e
         fcb   $72 r
         fcb   $69 i
         fcb   $65 e
         fcb   $73 s
         fcb   $3A :
         fcb   $0D
         fcb   $40 @
         fcb   $43 C
         fcb   $4F O
         fcb   $55 U
         fcb   $4E N
         fcb   $54 T
         fcb   $28 (
         fcb   $78 x
         fcb   $2E .
         fcb   $2E .
         fcb   $2E .
         fcb   $79 y
         fcb   $29 )
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $63 c
         fcb   $6F o
         fcb   $75 u
         fcb   $6E n
         fcb   $74 t
         fcb   $20
         fcb   $74 t
         fcb   $68 h
         fcb   $65 e
         fcb   $20
         fcb   $23 #
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $63 c
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $73 s
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $20
         fcb   $72 r
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $20
         fcb   $78 x
         fcb   $2E .
         fcb   $2E .
         fcb   $2E .
         fcb   $79 y
         fcb   $0D
         fcb   $40 @
         fcb   $53 S
         fcb   $55 U
         fcb   $4D M
         fcb   $28 (
         fcb   $78 x
         fcb   $2E .
         fcb   $2E .
         fcb   $2E .
         fcb   $79 y
         fcb   $29 )
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $73 s
         fcb   $75 u
         fcb   $6D m
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $76 v
         fcb   $61 a
         fcb   $6C l
         fcb   $75 u
         fcb   $65 e
         fcb   $73 s
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $63 c
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $73 s
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $20
         fcb   $72 r
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $20
         fcb   $78 x
         fcb   $2E .
         fcb   $2E .
         fcb   $2E .
         fcb   $79 y
         fcb   $0D
         fcb   $0A
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $48 H
         fcb   $69 i
         fcb   $74 t
         fcb   $20
         fcb   $61 a
         fcb   $6E n
         fcb   $79 y
         fcb   $20
         fcb   $6B k
         fcb   $65 e
         fcb   $79 y
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $65 e
         fcb   $20
         fcb   $70 p
         fcb   $61 a
         fcb   $67 g
         fcb   $65 e
         fcb   $20
         fcb   $33 3
         fcb   $11
         fcb   $40 @
         fcb   $41 A
         fcb   $56 V
         fcb   $45 E
         fcb   $52 R
         fcb   $41 A
         fcb   $47 G
         fcb   $45 E
         fcb   $28 (
         fcb   $78 x
         fcb   $2E .
         fcb   $2E .
         fcb   $2E .
         fcb   $79 y
         fcb   $29 )
         fcb   $20
         fcb   $20
         fcb   $61 a
         fcb   $76 v
         fcb   $65 e
         fcb   $72 r
         fcb   $61 a
         fcb   $67 g
         fcb   $65 e
         fcb   $20
         fcb   $76 v
         fcb   $61 a
         fcb   $6C l
         fcb   $75 u
         fcb   $65 e
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $63 c
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $73 s
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $20
         fcb   $72 r
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $20
         fcb   $78 x
         fcb   $2E .
         fcb   $2E .
         fcb   $2E .
         fcb   $79 y
         fcb   $0D
         fcb   $40 @
         fcb   $53 S
         fcb   $54 T
         fcb   $44 D
         fcb   $44 D
         fcb   $45 E
         fcb   $56 V
         fcb   $28 (
         fcb   $6D m
         fcb   $2C ,
         fcb   $78 x
         fcb   $2E .
         fcb   $2E .
         fcb   $2E .
         fcb   $79 y
         fcb   $29 )
         fcb   $20
         fcb   $73 s
         fcb   $74 t
         fcb   $61 a
         fcb   $6E n
         fcb   $64 d
         fcb   $61 a
         fcb   $72 r
         fcb   $64 d
         fcb   $20
         fcb   $64 d
         fcb   $65 e
         fcb   $76 v
         fcb   $2E .
         fcb   $0D
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $63 c
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $73 s
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $20
         fcb   $72 r
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $20
         fcb   $78 x
         fcb   $2E .
         fcb   $2E .
         fcb   $2E .
         fcb   $79 y
         fcb   $2C ,
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $6D m
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $74 t
         fcb   $73 s
         fcb   $20
         fcb   $6D m
         fcb   $65 e
         fcb   $74 t
         fcb   $68 h
         fcb   $6F o
         fcb   $64 d
         fcb   $3A :
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $3C <
         fcb   $30 0
         fcb   $20
         fcb   $3D =
         fcb   $20
         fcb   $70 p
         fcb   $6F o
         fcb   $70 p
         fcb   $75 u
         fcb   $6C l
         fcb   $61 a
         fcb   $74 t
         fcb   $69 i
         fcb   $6F o
         fcb   $6E n
         fcb   $3B ;
         fcb   $20
         fcb   $3E >
         fcb   $3D =
         fcb   $30 0
         fcb   $20
         fcb   $3D =
         fcb   $20
         fcb   $73 s
         fcb   $61 a
         fcb   $6D m
         fcb   $70 p
         fcb   $6C l
         fcb   $65 e
         fcb   $0D
         fcb   $0A
         fcb   $40 @
         fcb   $4D M
         fcb   $49 I
         fcb   $4E N
         fcb   $28 (
         fcb   $78 x
         fcb   $2E .
         fcb   $2E .
         fcb   $2E .
         fcb   $79 y
         fcb   $29 )
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $6C l
         fcb   $65 e
         fcb   $61 a
         fcb   $73 s
         fcb   $74 t
         fcb   $20
         fcb   $76 v
         fcb   $61 a
         fcb   $6C l
         fcb   $75 u
         fcb   $65 e
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $63 c
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $73 s
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $20
         fcb   $72 r
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $20
         fcb   $78 x
         fcb   $2E .
         fcb   $2E .
         fcb   $2E .
         fcb   $79 y
         fcb   $0D
         fcb   $40 @
         fcb   $4D M
         fcb   $41 A
         fcb   $58 X
         fcb   $28 (
         fcb   $78 x
         fcb   $2E .
         fcb   $2E .
         fcb   $2E .
         fcb   $79 y
         fcb   $29 )
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $67 g
         fcb   $72 r
         fcb   $65 e
         fcb   $61 a
         fcb   $74 t
         fcb   $65 e
         fcb   $73 s
         fcb   $74 t
         fcb   $20
         fcb   $76 v
         fcb   $61 a
         fcb   $6C l
         fcb   $75 u
         fcb   $65 e
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $63 c
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $73 s
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $20
         fcb   $72 r
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $20
         fcb   $78 x
         fcb   $2E .
         fcb   $2E .
         fcb   $2E .
         fcb   $79 y
         fcb   $0D
         fcb   $0A
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $48 H
         fcb   $69 i
         fcb   $74 t
         fcb   $20
         fcb   $61 a
         fcb   $6E n
         fcb   $79 y
         fcb   $20
         fcb   $6B k
         fcb   $65 e
         fcb   $79 y
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $65 e
         fcb   $20
         fcb   $70 p
         fcb   $61 a
         fcb   $67 g
         fcb   $65 e
         fcb   $20
         fcb   $34 4
         fcb   $11
         fcb   $40 @
         fcb   $4E N
         fcb   $50 P
         fcb   $56 V
         fcb   $28 (
         fcb   $72 r
         fcb   $2C ,
         fcb   $78 x
         fcb   $2E .
         fcb   $2E .
         fcb   $2E .
         fcb   $79 y
         fcb   $29 )
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $4E N
         fcb   $65 e
         fcb   $74 t
         fcb   $20
         fcb   $50 P
         fcb   $72 r
         fcb   $65 e
         fcb   $73 s
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $56 V
         fcb   $61 a
         fcb   $6C l
         fcb   $75 u
         fcb   $65 e
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $63 c
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $73 s
         fcb   $2C ,
         fcb   $20
         fcb   $72 r
         fcb   $61 a
         fcb   $74 t
         fcb   $65 e
         fcb   $20
         fcb   $72 r
         fcb   $0D
         fcb   $0A
         fcb   $49 I
         fcb   $6E n
         fcb   $64 d
         fcb   $65 e
         fcb   $78 x
         fcb   $69 i
         fcb   $6E n
         fcb   $67 g
         fcb   $3A :
         fcb   $0D
         fcb   $40 @
         fcb   $43 C
         fcb   $48 H
         fcb   $4F O
         fcb   $4F O
         fcb   $53 S
         fcb   $45 E
         fcb   $28 (
         fcb   $6E n
         fcb   $2C ,
         fcb   $78 x
         fcb   $2E .
         fcb   $2E .
         fcb   $2E .
         fcb   $79 y
         fcb   $29 )
         fcb   $20
         fcb   $76 v
         fcb   $61 a
         fcb   $6C l
         fcb   $75 u
         fcb   $65 e
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $6E n
         fcb   $74 t
         fcb   $68 h
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $63 c
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $20
         fcb   $69 i
         fcb   $6E n
         fcb   $20
         fcb   $72 r
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $20
         fcb   $78 x
         fcb   $2E .
         fcb   $2E .
         fcb   $2E .
         fcb   $79 y
         fcb   $0D
         fcb   $40 @
         fcb   $4C L
         fcb   $4F O
         fcb   $4F O
         fcb   $4B K
         fcb   $55 U
         fcb   $50 P
         fcb   $28 (
         fcb   $6E n
         fcb   $2C ,
         fcb   $78 x
         fcb   $2E .
         fcb   $2E .
         fcb   $2E .
         fcb   $79 y
         fcb   $2C ,
         fcb   $7A z
         fcb   $29 )
         fcb   $20
         fcb   $27 '
         fcb   $3E >
         fcb   $27 '
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $61 a
         fcb   $72 r
         fcb   $63 c
         fcb   $68 h
         fcb   $20
         fcb   $2D -
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $7A z
         fcb   $20
         fcb   $6F o
         fcb   $70 p
         fcb   $74 t
         fcb   $69 i
         fcb   $6F o
         fcb   $6E n
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $2D -
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $65 e
         fcb   $20
         fcb   $6D m
         fcb   $61 a
         fcb   $6E n
         fcb   $75 u
         fcb   $61 a
         fcb   $6C l
         fcb   $0D
         fcb   $40 @
         fcb   $49 I
         fcb   $4E N
         fcb   $44 D
         fcb   $45 E
         fcb   $58 X
         fcb   $28 (
         fcb   $6E n
         fcb   $2C ,
         fcb   $78 x
         fcb   $2E .
         fcb   $2E .
         fcb   $2E .
         fcb   $79 y
         fcb   $2C ,
         fcb   $7A z
         fcb   $29 )
         fcb   $20
         fcb   $20
         fcb   $27 '
         fcb   $3D =
         fcb   $27 '
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $61 a
         fcb   $72 r
         fcb   $63 c
         fcb   $68 h
         fcb   $20
         fcb   $2D -
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $7A z
         fcb   $20
         fcb   $6F o
         fcb   $70 p
         fcb   $74 t
         fcb   $69 i
         fcb   $6F o
         fcb   $6E n
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $2D -
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $65 e
         fcb   $20
         fcb   $6D m
         fcb   $61 a
         fcb   $6E n
         fcb   $75 u
         fcb   $61 a
         fcb   $6C l
         fcb   $0D
         fcb   $0A
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $48 H
         fcb   $69 i
         fcb   $74 t
         fcb   $20
         fcb   $61 a
         fcb   $6E n
         fcb   $79 y
         fcb   $20
         fcb   $6B k
         fcb   $65 e
         fcb   $79 y
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $65 e
         fcb   $20
         fcb   $70 p
         fcb   $61 a
         fcb   $67 g
         fcb   $65 e
         fcb   $20
         fcb   $35 5
         fcb   $11
         fcb   $4C L
         fcb   $6F o
         fcb   $67 g
         fcb   $69 i
         fcb   $63 c
         fcb   $61 a
         fcb   $6C l
         fcb   $3A :
         fcb   $0D
         fcb   $40 @
         fcb   $4E N
         fcb   $4F O
         fcb   $54 T
         fcb   $28 (
         fcb   $78 x
         fcb   $29 )
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $63 c
         fcb   $6F o
         fcb   $6D m
         fcb   $70 p
         fcb   $6C l
         fcb   $65 e
         fcb   $6D m
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $78 x
         fcb   $0D
         fcb   $40 @
         fcb   $41 A
         fcb   $4E N
         fcb   $44 D
         fcb   $28 (
         fcb   $78 x
         fcb   $2E .
         fcb   $2E .
         fcb   $2E .
         fcb   $79 y
         fcb   $29 )
         fcb   $20
         fcb   $74 t
         fcb   $72 r
         fcb   $75 u
         fcb   $65 e
         fcb   $20
         fcb   $69 i
         fcb   $66 f
         fcb   $20
         fcb   $61 a
         fcb   $6C l
         fcb   $6C l
         fcb   $20
         fcb   $74 t
         fcb   $72 r
         fcb   $75 u
         fcb   $65 e
         fcb   $0D
         fcb   $40 @
         fcb   $4F O
         fcb   $52 R
         fcb   $28 (
         fcb   $78 x
         fcb   $2E .
         fcb   $2E .
         fcb   $2E .
         fcb   $79 y
         fcb   $29 )
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $72 r
         fcb   $75 u
         fcb   $65 e
         fcb   $20
         fcb   $69 i
         fcb   $66 f
         fcb   $20
         fcb   $61 a
         fcb   $6E n
         fcb   $79 y
         fcb   $20
         fcb   $74 t
         fcb   $72 r
         fcb   $75 u
         fcb   $65 e
         fcb   $0D
         fcb   $40 @
         fcb   $45 E
         fcb   $4F O
         fcb   $52 R
         fcb   $28 (
         fcb   $78 x
         fcb   $2C ,
         fcb   $79 y
         fcb   $29 )
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $72 r
         fcb   $75 u
         fcb   $65 e
         fcb   $20
         fcb   $69 i
         fcb   $66 f
         fcb   $20
         fcb   $78 x
         fcb   $2F /
         fcb   $79 y
         fcb   $20
         fcb   $64 d
         fcb   $69 i
         fcb   $66 f
         fcb   $66 f
         fcb   $65 e
         fcb   $72 r
         fcb   $0D
         fcb   $40 @
         fcb   $49 I
         fcb   $46 F
         fcb   $28 (
         fcb   $63 c
         fcb   $2C ,
         fcb   $74 t
         fcb   $2C ,
         fcb   $66 f
         fcb   $29 )
         fcb   $20
         fcb   $20
         fcb   $65 e
         fcb   $76 v
         fcb   $61 a
         fcb   $6C l
         fcb   $75 u
         fcb   $61 a
         fcb   $74 t
         fcb   $65 e
         fcb   $20
         fcb   $63 c
         fcb   $2C ,
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $69 i
         fcb   $66 f
         fcb   $20
         fcb   $74 t
         fcb   $72 r
         fcb   $75 u
         fcb   $65 e
         fcb   $2C ,
         fcb   $20
         fcb   $72 r
         fcb   $65 e
         fcb   $74 t
         fcb   $75 u
         fcb   $72 r
         fcb   $6E n
         fcb   $20
         fcb   $74 t
         fcb   $3B ;
         fcb   $20
         fcb   $65 e
         fcb   $6C l
         fcb   $73 s
         fcb   $65 e
         fcb   $20
         fcb   $66 f
         fcb   $0D
         fcb   $40 @
         fcb   $49 I
         fcb   $53 S
         fcb   $4E N
         fcb   $41 A
         fcb   $28 (
         fcb   $58 X
         fcb   $29 )
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $72 r
         fcb   $75 u
         fcb   $65 e
         fcb   $20
         fcb   $69 i
         fcb   $66 f
         fcb   $20
         fcb   $63 c
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $20
         fcb   $78 x
         fcb   $20
         fcb   $3D =
         fcb   $20
         fcb   $3E >
         fcb   $4E N
         fcb   $41 A
         fcb   $3C <
         fcb   $0D
         fcb   $40 @
         fcb   $49 I
         fcb   $53 S
         fcb   $45 E
         fcb   $52 R
         fcb   $52 R
         fcb   $4F O
         fcb   $52 R
         fcb   $28 (
         fcb   $78 x
         fcb   $29 )
         fcb   $20
         fcb   $74 t
         fcb   $72 r
         fcb   $75 u
         fcb   $65 e
         fcb   $20
         fcb   $69 i
         fcb   $66 f
         fcb   $20
         fcb   $78 x
         fcb   $20
         fcb   $68 h
         fcb   $61 a
         fcb   $73 s
         fcb   $20
         fcb   $65 e
         fcb   $72 r
         fcb   $72 r
         fcb   $6F o
         fcb   $72 r
         fcb   $0D
         fcb   $40 @
         fcb   $54 T
         fcb   $52 R
         fcb   $55 U
         fcb   $45 E
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $72 r
         fcb   $65 e
         fcb   $74 t
         fcb   $75 u
         fcb   $72 r
         fcb   $6E n
         fcb   $20
         fcb   $6C l
         fcb   $6F o
         fcb   $67 g
         fcb   $69 i
         fcb   $63 c
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $74 t
         fcb   $72 r
         fcb   $75 u
         fcb   $65 e
         fcb   $0D
         fcb   $40 @
         fcb   $46 F
         fcb   $41 A
         fcb   $4C L
         fcb   $53 S
         fcb   $45 E
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $72 r
         fcb   $65 e
         fcb   $74 t
         fcb   $75 u
         fcb   $72 r
         fcb   $6E n
         fcb   $20
         fcb   $6C l
         fcb   $6F o
         fcb   $67 g
         fcb   $69 i
         fcb   $63 c
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $66 f
         fcb   $61 a
         fcb   $6C l
         fcb   $73 s
         fcb   $65 e
         fcb   $0D
         fcb   $0A
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $48 H
         fcb   $69 i
         fcb   $74 t
         fcb   $20
         fcb   $61 a
         fcb   $6E n
         fcb   $79 y
         fcb   $20
         fcb   $6B k
         fcb   $65 e
         fcb   $79 y
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $65 e
         fcb   $78 x
         fcb   $69 i
         fcb   $74 t
         fcb   $20
         fcb   $48 H
         fcb   $65 e
         fcb   $6C l
         fcb   $70 p
         fcb   $00

         fcc   "Arithmetic operators:"
         fcb   $0D
         fcb   $28 (
         fcb   $52 R
         fcb   $65 e
         fcb   $74 t
         fcb   $75 u
         fcb   $72 r
         fcb   $6E n
         fcb   $20
         fcb   $6E n
         fcb   $75 u
         fcb   $6D m
         fcb   $62 b
         fcb   $65 e
         fcb   $72 r
         fcb   $73 s
         fcb   $20
         fcb   $6F o
         fcb   $6E n
         fcb   $6C l
         fcb   $79 y
         fcb   $29 )
         fcb   $0D
         fcb   $0A
         fcb   $78 x
         fcb   $2B +
         fcb   $79 y
         fcb   $20
         fcb   $20
         fcb   $61 a
         fcb   $64 d
         fcb   $64 d
         fcb   $73 s
         fcb   $20
         fcb   $78 x
         fcb   $20
         fcb   $61 a
         fcb   $6E n
         fcb   $64 d
         fcb   $20
         fcb   $79 y
         fcb   $0D
         fcb   $78 x
         fcb   $2D -
         fcb   $79 y
         fcb   $20
         fcb   $20
         fcb   $73 s
         fcb   $75 u
         fcb   $62 b
         fcb   $74 t
         fcb   $72 r
         fcb   $61 a
         fcb   $63 c
         fcb   $74 t
         fcb   $73 s
         fcb   $20
         fcb   $79 y
         fcb   $20
         fcb   $66 f
         fcb   $72 r
         fcb   $6F o
         fcb   $6D m
         fcb   $20
         fcb   $78 x
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $28 (
         fcb   $75 u
         fcb   $73 s
         fcb   $65 e
         fcb   $20
         fcb   $30 0
         fcb   $2D -
         fcb   $78 x
         fcb   $20
         fcb   $66 f
         fcb   $6F o
         fcb   $72 r
         fcb   $20
         fcb   $6D m
         fcb   $6F o
         fcb   $6E n
         fcb   $61 a
         fcb   $64 d
         fcb   $69 i
         fcb   $63 c
         fcb   $20
         fcb   $6D m
         fcb   $69 i
         fcb   $6E n
         fcb   $75 u
         fcb   $73 s
         fcb   $29 )
         fcb   $0D
         fcb   $78 x
         fcb   $2A *
         fcb   $79 y
         fcb   $20
         fcb   $20
         fcb   $6D m
         fcb   $75 u
         fcb   $6C l
         fcb   $74 t
         fcb   $69 i
         fcb   $70 p
         fcb   $6C l
         fcb   $69 i
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $78 x
         fcb   $20
         fcb   $62 b
         fcb   $79 y
         fcb   $20
         fcb   $79 y
         fcb   $0D
         fcb   $78 x
         fcb   $2F /
         fcb   $79 y
         fcb   $20
         fcb   $20
         fcb   $64 d
         fcb   $69 i
         fcb   $76 v
         fcb   $69 i
         fcb   $64 d
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $78 x
         fcb   $20
         fcb   $62 b
         fcb   $79 y
         fcb   $20
         fcb   $79 y
         fcb   $0D
         fcb   $78 x
         fcb   $5E ^
         fcb   $79 y
         fcb   $20
         fcb   $20
         fcb   $72 r
         fcb   $61 a
         fcb   $69 i
         fcb   $73 s
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $78 x
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $79 y
         fcb   $20
         fcb   $70 p
         fcb   $6F o
         fcb   $77 w
         fcb   $65 e
         fcb   $72 r
         fcb   $0D
         fcb   $0A
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $48 H
         fcb   $69 i
         fcb   $74 t
         fcb   $20
         fcb   $61 a
         fcb   $6E n
         fcb   $79 y
         fcb   $20
         fcb   $6B k
         fcb   $65 e
         fcb   $79 y
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $65 e
         fcb   $20
         fcb   $70 p
         fcb   $61 a
         fcb   $67 g
         fcb   $65 e
         fcb   $20
         fcb   $32 2
         fcb   $11
         fcb   $4C L
         fcb   $6F o
         fcb   $67 g
         fcb   $69 i
         fcb   $63 c
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $6F o
         fcb   $70 p
         fcb   $65 e
         fcb   $72 r
         fcb   $61 a
         fcb   $74 t
         fcb   $6F o
         fcb   $72 r
         fcb   $73 s
         fcb   $3A :
         fcb   $0D
         fcb   $28 (
         fcb   $52 R
         fcb   $65 e
         fcb   $74 t
         fcb   $75 u
         fcb   $72 r
         fcb   $6E n
         fcb   $20
         fcb   $54 T
         fcb   $72 r
         fcb   $75 u
         fcb   $65 e
         fcb   $2F /
         fcb   $46 F
         fcb   $61 a
         fcb   $6C l
         fcb   $73 s
         fcb   $65 e
         fcb   $20
         fcb   $6F o
         fcb   $6E n
         fcb   $6C l
         fcb   $79 y
         fcb   $29 )
         fcb   $0D
         fcb   $0A
         fcb   $78 x
         fcb   $3D =
         fcb   $79 y
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $72 r
         fcb   $75 u
         fcb   $65 e
         fcb   $20
         fcb   $69 i
         fcb   $66 f
         fcb   $20
         fcb   $78 x
         fcb   $20
         fcb   $65 e
         fcb   $71 q
         fcb   $75 u
         fcb   $61 a
         fcb   $6C l
         fcb   $73 s
         fcb   $20
         fcb   $79 y
         fcb   $0D
         fcb   $78 x
         fcb   $3C <
         fcb   $3E >
         fcb   $79 y
         fcb   $20
         fcb   $74 t
         fcb   $72 r
         fcb   $75 u
         fcb   $65 e
         fcb   $20
         fcb   $69 i
         fcb   $66 f
         fcb   $20
         fcb   $78 x
         fcb   $20
         fcb   $64 d
         fcb   $6F o
         fcb   $65 e
         fcb   $73 s
         fcb   $6E n
         fcb   $27 '
         fcb   $74 t
         fcb   $20
         fcb   $65 e
         fcb   $71 q
         fcb   $75 u
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $79 y
         fcb   $0D
         fcb   $78 x
         fcb   $3E >
         fcb   $79 y
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $72 r
         fcb   $75 u
         fcb   $65 e
         fcb   $20
         fcb   $69 i
         fcb   $66 f
         fcb   $20
         fcb   $78 x
         fcb   $20
         fcb   $67 g
         fcb   $72 r
         fcb   $65 e
         fcb   $61 a
         fcb   $74 t
         fcb   $65 e
         fcb   $72 r
         fcb   $20
         fcb   $74 t
         fcb   $68 h
         fcb   $61 a
         fcb   $6E n
         fcb   $20
         fcb   $79 y
         fcb   $0D
         fcb   $78 x
         fcb   $3E >
         fcb   $3D =
         fcb   $79 y
         fcb   $2C ,
         fcb   $78 x
         fcb   $3D =
         fcb   $3E >
         fcb   $79 y
         fcb   $20
         fcb   $74 t
         fcb   $72 r
         fcb   $75 u
         fcb   $65 e
         fcb   $20
         fcb   $69 i
         fcb   $66 f
         fcb   $20
         fcb   $78 x
         fcb   $20
         fcb   $69 i
         fcb   $73 s
         fcb   $20
         fcb   $67 g
         fcb   $72 r
         fcb   $65 e
         fcb   $61 a
         fcb   $74 t
         fcb   $65 e
         fcb   $72 r
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $68 h
         fcb   $61 a
         fcb   $6E n
         fcb   $20
         fcb   $6F o
         fcb   $72 r
         fcb   $20
         fcb   $65 e
         fcb   $71 q
         fcb   $75 u
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $79 y
         fcb   $0D
         fcb   $78 x
         fcb   $3C <
         fcb   $3D =
         fcb   $79 y
         fcb   $2C ,
         fcb   $78 x
         fcb   $3D =
         fcb   $3C <
         fcb   $79 y
         fcb   $20
         fcb   $74 t
         fcb   $72 r
         fcb   $75 u
         fcb   $65 e
         fcb   $20
         fcb   $69 i
         fcb   $66 f
         fcb   $20
         fcb   $78 x
         fcb   $20
         fcb   $69 i
         fcb   $73 s
         fcb   $20
         fcb   $6C l
         fcb   $65 e
         fcb   $73 s
         fcb   $73 s
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $74 t
         fcb   $68 h
         fcb   $61 a
         fcb   $6E n
         fcb   $20
         fcb   $6F o
         fcb   $72 r
         fcb   $20
         fcb   $65 e
         fcb   $71 q
         fcb   $75 u
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $79 y
         fcb   $0D
         fcb   $0A
         fcc   "   Hit any key to see page 3"
         fcb   $11
         fcb   $20
         fcb   $20
         fcb   $4D M
         fcb   $61 a
         fcb   $78 x
         fcb   $69 i
         fcb   $6D m
         fcb   $75 u
         fcb   $6D m
         fcb   $20
         fcb   $6E n
         fcb   $75 u
         fcb   $6D m
         fcb   $62 b
         fcb   $65 e
         fcb   $72 r
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $74 t
         fcb   $65 e
         fcb   $72 r
         fcb   $6D m
         fcb   $73 s
         fcb   $0D
         fcb   $28 (
         fcb   $70 p
         fcb   $65 e
         fcb   $6E n
         fcb   $64 d
         fcb   $69 i
         fcb   $6E n
         fcb   $67 g
         fcb   $20
         fcb   $61 a
         fcb   $64 d
         fcb   $64 d
         fcb   $69 i
         fcb   $74 t
         fcb   $69 i
         fcb   $6F o
         fcb   $6E n
         fcb   $73 s
         fcb   $29 )
         fcb   $20
         fcb   $69 i
         fcb   $73 s
         fcb   $20
         fcb   $31 1
         fcb   $31 1
         fcb   $2E .
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $50 P
         fcb   $61 a
         fcb   $72 r
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $68 h
         fcb   $65 e
         fcb   $73 s
         fcb   $65 e
         fcb   $73 s
         fcb   $20
         fcb   $77 w
         fcb   $69 i
         fcb   $74 t
         fcb   $68 h
         fcb   $69 i
         fcb   $6E n
         fcb   $20
         fcb   $74 t
         fcb   $65 e
         fcb   $72 r
         fcb   $6D m
         fcb   $73 s
         fcb   $20
         fcb   $6D m
         fcb   $61 a
         fcb   $79 y
         fcb   $0D
         fcb   $62 b
         fcb   $65 e
         fcb   $20
         fcb   $6E n
         fcb   $65 e
         fcb   $73 s
         fcb   $74 t
         fcb   $65 e
         fcb   $64 d
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $61 a
         fcb   $6E n
         fcb   $79 y
         fcb   $20
         fcb   $64 d
         fcb   $65 e
         fcb   $70 p
         fcb   $74 t
         fcb   $68 h
         fcb   $2E .
         fcb   $0D
         fcb   $20
         fcb   $20
         fcb   $54 T
         fcb   $6F o
         fcb   $20
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $65 e
         fcb   $72 r
         fcb   $20
         fcb   $65 e
         fcb   $78 x
         fcb   $70 p
         fcb   $72 r
         fcb   $65 e
         fcb   $73 s
         fcb   $73 s
         fcb   $69 i
         fcb   $6F o
         fcb   $6E n
         fcb   $2C ,
         fcb   $20
         fcb   $66 f
         fcb   $69 i
         fcb   $72 r
         fcb   $73 s
         fcb   $74 t
         fcb   $0D
         fcb   $63 c
         fcb   $68 h
         fcb   $61 a
         fcb   $72 r
         fcb   $61 a
         fcb   $63 c
         fcb   $74 t
         fcb   $65 e
         fcb   $72 r
         fcb   $20
         fcb   $6D m
         fcb   $75 u
         fcb   $73 s
         fcb   $74 t
         fcb   $6E n
         fcb   $27 '
         fcb   $74 t
         fcb   $20
         fcb   $62 b
         fcb   $65 e
         fcb   $20
         fcb   $61 a
         fcb   $6C l
         fcb   $70 p
         fcb   $68 h
         fcb   $61 a
         fcb   $62 b
         fcb   $65 e
         fcb   $74 t
         fcb   $69 i
         fcb   $63 c
         fcb   $0D
         fcb   $46 F
         fcb   $6F o
         fcb   $72 r
         fcb   $20
         fcb   $65 e
         fcb   $78 x
         fcb   $61 a
         fcb   $6D m
         fcb   $70 p
         fcb   $6C l
         fcb   $65 e
         fcb   $2C ,
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $20
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $65 e
         fcb   $72 r
         fcb   $20
         fcb   $41 A
         fcb   $31 1
         fcb   $2B +
         fcb   $41 A
         fcb   $32 2
         fcb   $2C ,
         fcb   $0D
         fcb   $74 t
         fcb   $79 y
         fcb   $70 p
         fcb   $65 e
         fcb   $20
         fcb   $27 '
         fcb   $2B +
         fcb   $41 A
         fcb   $31 1
         fcb   $2B +
         fcb   $41 A
         fcb   $32 2
         fcb   $27 '
         fcb   $2E .
         fcb   $0D
         fcc   "  To enter numeric as a label,"
         fcb   $0D
         fcc   "use leading single-quote (')."
         fcb   $0D
         fcb   $0A
         fcc   "   Hit any key to exit Help"
         fcb   $00
         fcc   " >AE<  Bad argument error"
         fcb   $0D
         fcc   " >D0<  Divide by zero attempted"
         fcb   $0D
         fcc   " >ER<  General purpose error"
         fcb   $0D
         fcb   $20
         fcb   $3E >
         fcb   $45 E
         fcb   $58 X
         fcb   $3C <
         fcb   $20
         fcb   $20
         fcb   $45 E
         fcb   $78 x
         fcb   $70 p
         fcb   $6F o
         fcb   $6E n
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $20
         fcb   $74 t
         fcb   $6F o
         fcb   $6F o
         fcb   $20
         fcb   $6C l
         fcb   $61 a
         fcb   $72 r
         fcb   $67 g
         fcb   $65 e
         fcb   $0D
         fcb   $20
         fcb   $3E >
         fcb   $48 H
         fcb   $4F O
         fcb   $3C <
         fcb   $20
         fcb   $20
         fcb   $48 H
         fcb   $6F o
         fcb   $6C l
         fcb   $64 d
         fcb   $65 e
         fcb   $72 r
         fcb   $20
         fcb   $6F o
         fcb   $76 v
         fcb   $65 e
         fcb   $72 r
         fcb   $66 f
         fcb   $6C l
         fcb   $6F o
         fcb   $77 w
         fcb   $20
         fcb   $65 e
         fcb   $72 r
         fcb   $72 r
         fcb   $6F o
         fcb   $72 r
         fcb   $0D
         fcb   $20
         fcb   $3E >
         fcb   $4C L
         fcb   $47 G
         fcb   $3C <
         fcb   $20
         fcb   $20
         fcb   $4C L
         fcb   $6F o
         fcb   $67 g
         fcb   $69 i
         fcb   $63 c
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $65 e
         fcb   $72 r
         fcb   $72 r
         fcb   $6F o
         fcb   $72 r
         fcb   $0D
         fcc   " >LN<  Negative/zero logarithm"
         fcb   $0D
         fcc   " >NA<  Not available"
         fcb   $0D
         fcb   $20
         fcb   $3E >
         fcb   $4E N
         fcb   $52 R
         fcb   $3C <
         fcb   $20
         fcb   $20
         fcb   $4E N
         fcb   $65 e
         fcb   $67 g
         fcb   $61 a
         fcb   $74 t
         fcb   $69 i
         fcb   $76 v
         fcb   $65 e
         fcb   $20
         fcb   $72 r
         fcb   $6F o
         fcb   $6F o
         fcb   $74 t
         fcb   $20
         fcb   $61 a
         fcb   $74 t
         fcb   $74 t
         fcb   $65 e
         fcb   $6D m
         fcb   $70 p
         fcb   $74 t
         fcb   $65 e
         fcb   $64 d
         fcb   $0D
         fcb   $20
         fcb   $3E >
         fcb   $4F O
         fcb   $56 V
         fcb   $3C <
         fcb   $20
         fcb   $20
         fcb   $4F O
         fcb   $76 v
         fcb   $65 e
         fcb   $72 r
         fcb   $66 f
         fcb   $6C l
         fcb   $6F o
         fcb   $77 w
         fcb   $20
         fcb   $65 e
         fcb   $72 r
         fcb   $72 r
         fcb   $6F o
         fcb   $72 r
         fcb   $0D
         fcb   $20
         fcb   $3E >
         fcb   $52 R
         fcb   $45 E
         fcb   $3C <
         fcb   $20
         fcb   $20
         fcb   $52 R
         fcb   $65 e
         fcb   $66 f
         fcb   $65 e
         fcb   $72 r
         fcb   $65 e
         fcb   $6E n
         fcb   $63 c
         fcb   $65 e
         fcb   $20
         fcb   $65 e
         fcb   $72 r
         fcb   $72 r
         fcb   $6F o
         fcb   $72 r
         fcb   $0D
         fcb   $20
         fcb   $3E >
         fcb   $52 R
         fcb   $4E N
         fcb   $3C <
         fcb   $20
         fcb   $20
         fcb   $52 R
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $20
         fcb   $65 e
         fcb   $72 r
         fcb   $72 r
         fcb   $6F o
         fcb   $72 r
         fcb   $0D
         fcb   $20
         fcb   $3E >
         fcb   $53 S
         fcb   $4E N
         fcb   $3C <
         fcb   $20
         fcb   $20
         fcb   $53 S
         fcb   $79 y
         fcb   $6E n
         fcb   $74 t
         fcb   $61 a
         fcb   $78 x
         fcb   $20
         fcb   $65 e
         fcb   $72 r
         fcb   $72 r
         fcb   $6F o
         fcb   $72 r
         fcb   $00

         fcc   "Path table full"
         fcb   $00
         fcc   "Illegal path number"
         fcb   $00
         fcc   "Int. table full"
         fcb   $00
         fcc   "Illegal I/O mode."
         fcb   $00
         fcb   $44 D
         fcb   $65 e
         fcb   $76 v
         fcb   $69 i
         fcb   $63 c
         fcb   $65 e
         fcb   $20
         fcb   $6F o
         fcb   $76 v
         fcb   $65 e
         fcb   $72 r
         fcb   $66 f
         fcb   $6C l
         fcb   $6F o
         fcb   $77 w
         fcb   $00
         fcb   $49 I
         fcb   $6C l
         fcb   $6C l
         fcb   $65 e
         fcb   $67 g
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $49 I
         fcb   $44 D
         fcb   $20
         fcb   $62 b
         fcb   $6C l
         fcb   $6F o
         fcb   $63 c
         fcb   $6B k
         fcb   $00
         fcb   $4D M
         fcb   $6F o
         fcb   $64 d
         fcb   $75 u
         fcb   $6C l
         fcb   $65 e
         fcb   $20
         fcb   $64 d
         fcb   $69 i
         fcb   $72 r
         fcb   $2E .
         fcb   $20
         fcb   $66 f
         fcb   $75 u
         fcb   $6C l
         fcb   $6C l
         fcb   $00
         fcb   $4D M
         fcb   $65 e
         fcb   $6D m
         fcb   $6F o
         fcb   $72 r
         fcb   $79 y
         fcb   $20
         fcb   $66 f
         fcb   $75 u
         fcb   $6C l
         fcb   $6C l
         fcb   $00
         fcb   $55 U
         fcb   $6E n
         fcb   $6B k
         fcb   $6E n
         fcb   $6F o
         fcb   $77 w
         fcb   $6E n
         fcb   $20
         fcb   $72 r
         fcb   $65 e
         fcb   $71 q
         fcb   $75 u
         fcb   $65 e
         fcb   $73 s
         fcb   $74 t
         fcb   $00
         fcb   $4D M
         fcb   $6F o
         fcb   $64 d
         fcb   $75 u
         fcb   $6C l
         fcb   $65 e
         fcb   $20
         fcb   $62 b
         fcb   $75 u
         fcb   $73 s
         fcb   $79 y
         fcb   $00
         fcb   $42 B
         fcb   $61 a
         fcb   $64 d
         fcb   $20
         fcb   $62 b
         fcb   $6F o
         fcb   $75 u
         fcb   $6E n
         fcb   $64 d
         fcb   $61 a
         fcb   $72 r
         fcb   $79 y
         fcb   $00
         fcb   $45 E
         fcb   $6E n
         fcb   $64 d
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $66 f
         fcb   $69 i
         fcb   $6C l
         fcb   $65 e
         fcb   $00
         fcb   $4E N
         fcb   $6F o
         fcb   $6E n
         fcb   $2D -
         fcb   $61 a
         fcb   $6C l
         fcb   $6C l
         fcb   $6F o
         fcb   $63 c
         fcb   $61 a
         fcb   $74 t
         fcb   $65 e
         fcb   $64 d
         fcb   $20
         fcb   $6D m
         fcb   $65 e
         fcb   $6D m
         fcb   $2E .
         fcb   $00
         fcb   $4E N
         fcb   $6F o
         fcb   $6E n
         fcb   $2D -
         fcb   $65 e
         fcb   $78 x
         fcb   $69 i
         fcb   $73 s
         fcb   $74 t
         fcb   $69 i
         fcb   $6E n
         fcb   $67 g
         fcb   $20
         fcb   $73 s
         fcb   $65 e
         fcb   $67 g
         fcb   $2E .
         fcb   $00
         fcb   $4E N
         fcb   $6F o
         fcb   $20
         fcb   $70 p
         fcb   $65 e
         fcb   $72 r
         fcb   $6D m
         fcb   $69 i
         fcb   $73 s
         fcb   $73 s
         fcb   $69 i
         fcb   $6F o
         fcb   $6E n
         fcb   $00
         fcb   $42 B
         fcb   $61 a
         fcb   $64 d
         fcb   $20
         fcb   $70 p
         fcb   $61 a
         fcb   $74 t
         fcb   $68 h
         fcb   $20
         fcb   $6E n
         fcb   $61 a
         fcb   $6D m
         fcb   $65 e
         fcb   $00
         fcb   $46 F
         fcb   $69 i
         fcb   $6C l
         fcb   $65 e
         fcb   $2F /
         fcb   $64 d
         fcb   $65 e
         fcb   $76 v
         fcb   $2E .
         fcb   $20
         fcb   $6E n
         fcb   $6F o
         fcb   $74 t
         fcb   $20
         fcb   $66 f
         fcb   $6F o
         fcb   $75 u
         fcb   $6E n
         fcb   $64 d
         fcb   $00
         fcb   $53 S
         fcb   $65 e
         fcb   $67 g
         fcb   $6D m
         fcb   $65 e
         fcb   $6E n
         fcb   $74 t
         fcb   $20
         fcb   $6C l
         fcb   $69 i
         fcb   $73 s
         fcb   $74 t
         fcb   $20
         fcb   $66 f
         fcb   $69 i
         fcb   $6C l
         fcb   $6C l
         fcb   $65 e
         fcb   $64 d
         fcb   $00
         fcb   $46 F
         fcb   $69 i
         fcb   $6C l
         fcb   $65 e
         fcb   $20
         fcb   $61 a
         fcb   $6C l
         fcb   $72 r
         fcb   $65 e
         fcb   $61 a
         fcb   $64 d
         fcb   $79 y
         fcb   $20
         fcb   $65 e
         fcb   $78 x
         fcb   $69 i
         fcb   $73 s
         fcb   $74 t
         fcb   $73 s
         fcb   $00
         fcb   $49 I
         fcb   $6C l
         fcb   $6C l
         fcb   $65 e
         fcb   $67 g
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $61 a
         fcb   $64 d
         fcb   $64 d
         fcb   $72 r
         fcb   $65 e
         fcb   $73 s
         fcb   $73 s
         fcb   $00
         fcb   $49 I
         fcb   $6C l
         fcb   $6C l
         fcb   $65 e
         fcb   $67 g
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $62 b
         fcb   $6C l
         fcb   $6F o
         fcb   $63 c
         fcb   $6B k
         fcb   $20
         fcb   $73 s
         fcb   $69 i
         fcb   $7A z
         fcb   $65 e
         fcb   $00
         fcb   $4E N
         fcb   $6F o
         fcb   $6E n
         fcb   $2D -
         fcb   $65 e
         fcb   $78 x
         fcb   $69 i
         fcb   $73 s
         fcb   $74 t
         fcb   $69 i
         fcb   $6E n
         fcb   $67 g
         fcb   $20
         fcb   $6D m
         fcb   $6F o
         fcb   $64 d
         fcb   $75 u
         fcb   $6C l
         fcb   $65 e
         fcb   $00
         fcb   $53 S
         fcb   $65 e
         fcb   $63 c
         fcb   $74 t
         fcb   $6F o
         fcb   $72 r
         fcb   $20
         fcb   $6F o
         fcb   $75 u
         fcb   $74 t
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $72 r
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $00
         fcb   $44 D
         fcb   $65 e
         fcb   $61 a
         fcb   $6C l
         fcb   $6C l
         fcb   $6F o
         fcb   $63 c
         fcb   $61 a
         fcb   $74 t
         fcb   $69 i
         fcb   $6E n
         fcb   $67 g
         fcb   $20
         fcb   $73 s
         fcb   $74 t
         fcb   $61 a
         fcb   $63 c
         fcb   $6B k
         fcb   $00
         fcb   $49 I
         fcb   $6C l
         fcb   $6C l
         fcb   $65 e
         fcb   $67 g
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $70 p
         fcb   $72 r
         fcb   $6F o
         fcb   $63 c
         fcb   $65 e
         fcb   $73 s
         fcb   $73 s
         fcb   $20
         fcb   $49 I
         fcb   $44 D
         fcb   $00
         fcb   $49 I
         fcb   $6C l
         fcb   $6C l
         fcb   $65 e
         fcb   $67 g
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $73 s
         fcb   $69 i
         fcb   $67 g
         fcb   $6E n
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $63 c
         fcb   $6F o
         fcb   $64 d
         fcb   $65 e
         fcb   $00
         fcb   $4E N
         fcb   $6F o
         fcb   $20
         fcb   $63 c
         fcb   $68 h
         fcb   $69 i
         fcb   $6C l
         fcb   $64 d
         fcb   $72 r
         fcb   $65 e
         fcb   $6E n
         fcb   $00
         fcb   $49 I
         fcb   $6C l
         fcb   $6C l
         fcb   $65 e
         fcb   $67 g
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $53 S
         fcb   $57 W
         fcb   $49 I
         fcb   $20
         fcb   $63 c
         fcb   $6F o
         fcb   $64 d
         fcb   $65 e
         fcb   $00
         fcb   $4B K
         fcb   $65 e
         fcb   $79 y
         fcb   $62 b
         fcb   $6F o
         fcb   $61 a
         fcb   $72 r
         fcb   $64 d
         fcb   $20
         fcb   $61 a
         fcb   $62 b
         fcb   $6F o
         fcb   $72 r
         fcb   $74 t
         fcb   $00
         fcb   $50 P
         fcb   $72 r
         fcb   $6F o
         fcb   $63 c
         fcb   $65 e
         fcb   $73 s
         fcb   $73 s
         fcb   $20
         fcb   $74 t
         fcb   $61 a
         fcb   $62 b
         fcb   $6C l
         fcb   $65 e
         fcb   $20
         fcb   $66 f
         fcb   $75 u
         fcb   $6C l
         fcb   $6C l
         fcb   $00
         fcb   $49 I
         fcb   $6C l
         fcb   $6C l
         fcb   $65 e
         fcb   $67 g
         fcb   $61 a
         fcb   $6C l
         fcb   $20
         fcb   $66 f
         fcb   $6F o
         fcb   $72 r
         fcb   $6B k
         fcb   $20
         fcb   $61 a
         fcb   $72 r
         fcb   $65 e
         fcb   $61 a
         fcb   $00
         fcb   $4B K
         fcb   $6E n
         fcb   $6F o
         fcb   $77 w
         fcb   $6E n
         fcb   $20
         fcb   $6D m
         fcb   $6F o
         fcb   $64 d
         fcb   $75 u
         fcb   $6C l
         fcb   $65 e
         fcb   $00
         fcb   $42 B
         fcb   $61 a
         fcb   $64 d
         fcb   $20
         fcb   $6D m
         fcb   $6F o
         fcb   $64 d
         fcb   $75 u
         fcb   $6C l
         fcb   $65 e
         fcb   $20
         fcb   $43 C
         fcb   $52 R
         fcb   $43 C
         fcb   $00
         fcb   $55 U
         fcb   $6E n
         fcb   $70 p
         fcb   $72 r
         fcb   $6F o
         fcb   $63 c
         fcb   $65 e
         fcb   $73 s
         fcb   $73 s
         fcb   $65 e
         fcb   $64 d
         fcb   $20
         fcb   $73 s
         fcb   $69 i
         fcb   $67 g
         fcb   $6E n
         fcb   $61 a
         fcb   $6C l
         fcb   $00
         fcb   $4E N
         fcb   $6F o
         fcb   $6E n
         fcb   $2D -
         fcb   $65 e
         fcb   $78 x
         fcb   $65 e
         fcb   $63 c
         fcb   $75 u
         fcb   $74 t
         fcb   $61 a
         fcb   $62 b
         fcb   $6C l
         fcb   $65 e
         fcb   $20
         fcb   $6D m
         fcb   $6F o
         fcb   $64 d
         fcb   $2E .
         fcb   $00
         fcb   $4E N
         fcb   $75 u
         fcb   $6D m
         fcb   $62 b
         fcb   $65 e
         fcb   $72 r
         fcb   $20
         fcb   $6F o
         fcb   $75 u
         fcb   $74 t
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $72 r
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $00
         fcb   $53 S
         fcb   $65 e
         fcb   $63 c
         fcb   $74 t
         fcb   $6F o
         fcb   $72 r
         fcb   $20
         fcb   $6F o
         fcb   $75 u
         fcb   $74 t
         fcb   $20
         fcb   $6F o
         fcb   $66 f
         fcb   $20
         fcb   $72 r
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $00
         fcb   $57 W
         fcb   $72 r
         fcb   $69 i
         fcb   $74 t
         fcb   $65 e
         fcb   $20
         fcb   $70 p
         fcb   $72 r
         fcb   $6F o
         fcb   $74 t
         fcb   $65 e
         fcb   $63 c
         fcb   $74 t
         fcb   $00
         fcb   $43 C
         fcb   $68 h
         fcb   $65 e
         fcb   $63 c
         fcb   $6B k
         fcb   $73 s
         fcb   $75 u
         fcb   $6D m
         fcb   $20
         fcb   $65 e
         fcb   $72 r
         fcb   $72 r
         fcb   $6F o
         fcb   $72 r
         fcb   $00
         fcb   $52 R
         fcb   $65 e
         fcb   $61 a
         fcb   $64 d
         fcb   $20
         fcb   $65 e
         fcb   $72 r
         fcb   $72 r
         fcb   $6F o
         fcb   $72 r
         fcb   $00
         fcb   $57 W
         fcb   $72 r
         fcb   $69 i
         fcb   $74 t
         fcb   $65 e
         fcb   $20
         fcb   $65 e
         fcb   $72 r
         fcb   $72 r
         fcb   $6F o
         fcb   $72 r
         fcb   $00
         fcb   $44 D
         fcb   $65 e
         fcb   $76 v
         fcb   $69 i
         fcb   $63 c
         fcb   $65 e
         fcb   $20
         fcb   $6E n
         fcb   $6F o
         fcb   $74 t
         fcb   $20
         fcb   $72 r
         fcb   $65 e
         fcb   $61 a
         fcb   $64 d
         fcb   $79 y
         fcb   $00
         fcb   $53 S
         fcb   $65 e
         fcb   $65 e
         fcb   $6B k
         fcb   $20
         fcb   $65 e
         fcb   $72 r
         fcb   $72 r
         fcb   $6F o
         fcb   $72 r
         fcb   $00
         fcb   $4D M
         fcb   $65 e
         fcb   $64 d
         fcb   $69 i
         fcb   $61 a
         fcb   $20
         fcb   $66 f
         fcb   $75 u
         fcb   $6C l
         fcb   $6C l
         fcb   $00
         fcb   $44 D
         fcb   $65 e
         fcb   $76 v
         fcb   $69 i
         fcb   $63 c
         fcb   $65 e
         fcb   $20
         fcb   $6D m
         fcb   $69 i
         fcb   $73 s
         fcb   $6D m
         fcb   $61 a
         fcb   $74 t
         fcb   $63 c
         fcb   $68 h
         fcb   $2E .
         fcb   $00
         fcb   $44 D
         fcb   $65 e
         fcb   $76 v
         fcb   $69 i
         fcb   $63 c
         fcb   $65 e
         fcb   $20
         fcb   $62 b
         fcb   $75 u
         fcb   $73 s
         fcb   $79 y
         fcb   $00
         fcb   $44 D
         fcb   $65 e
         fcb   $76 v
         fcb   $69 i
         fcb   $63 c
         fcb   $65 e
         fcb   $20
         fcb   $49 I
         fcb   $44 D
         fcb   $20
         fcb   $63 c
         fcb   $68 h
         fcb   $61 a
         fcb   $6E n
         fcb   $67 g
         fcb   $65 e
         fcb   $64 d
         fcb   $2E .
         fcb   $00
         fcc   "Indirect file error"
         fcb   $00
         fcb   $49 I
         fcb   $6E n
         fcb   $64 d
         fcb   $69 i
         fcb   $72 r
         fcb   $65 e
         fcb   $63 c
         fcb   $74 t
         fcb   $20
         fcb   $66 f
         fcb   $69 i
         fcb   $6C l
         fcb   $65 e
         fcb   $00
M2CC1    fcc   "Un"
M2CC3    fcc   "known error code"
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $10
         fcb   $00
         fcb   $24 $
         fcb   $00
         fcb   $34 4
         fcb   $00
         fcb   $46 F
         fcb   $00
         fcb   $56 V
         fcb   $00
         fcb   $67 g
         fcb   $00
         fcb   $78 x
         fcb   $00
         fcb   $84
         fcb   $00
         fcb   $94
         fcb   $00
         fcb   $A0
         fcb   $00
         fcb   $AD -
         fcb   $00
         fcb   $B9 9
         fcb   $00
         fcb   $CC L
         fcb   $00
         fcb   $DE ^
         fcb   $00
         fcb   $EC l
         fcb   $00
         fcb   $FA z
         fcb   $01
         fcb   $0E
         fcb   $01
         fcb   $22 "
         fcb   $01
         fcb   $36 6
         fcb   $01
         fcb   $46 F
         fcb   $01
         fcb   $59 Y
         fcb   $01
         fcb   $6D m
         fcb   $01
         fcb   $81
         fcb   $01
         fcb   $94
         fcb   $01
         fcb   $A7 '
         fcb   $01
         fcb   $BB ;
         fcb   $01
         fcb   $C7 G
         fcb   $01
         fcb   $D8 X
         fcb   $01
         fcb   $E7 g
         fcb   $01
         fcb   $FA z
         fcb   $02
         fcb   $0C
         fcb   $02
         fcb   $19
         fcb   $02
         fcb   $28 (
         fcb   $02
         fcb   $3B ;
         fcb   $03
         fcb   $24 $
         fcb   $03
         fcb   $24 $
         fcb   $03
         fcb   $24 $
         fcb   $03
         fcb   $24 $
         fcb   $03
         fcb   $24 $
         fcb   $02
         fcb   $4F O
         fcb   $02
         fcb   $63 c
         fcb   $02
         fcb   $77 w
         fcb   $02
         fcb   $85
         fcb   $02
         fcb   $94
         fcb   $02
         fcb   $9F
         fcb   $02
         fcb   $AB +
         fcb   $02
         fcb   $BC <
         fcb   $02
         fcb   $C7 G
         fcb   $02
         fcb   $D2 R
         fcb   $02
         fcb   $E3 c
         fcb   $02
         fcb   $EF o
         fcb   $03
         fcb   $02
         fcb   $03
         fcb   $16
         fcb   $03
         fcb   $24 $
         fcb   $00
         fcb   $00
         fcb   $02
         fcb   $58 X
         fcb   $14
         fcb   $B0 0
         fcb   $07
         fcb   $FA z
         fcb   $03
         fcb   $FB
         fcb   $09
         fcb   $28 (
         fcb   $08
         fcb   $69 i
         fcb   $06
         fcb   $BE >
         fcb   $0D
         fcb   $5B [
         fcb   $06
         fcb   $59 Y
         fcb   $0C
         fcb   $40 @
         fcb   $03
         fcb   $B6 6
         fcb   $05
         fcb   $DD ]
         fcb   $0A
         fcb   $5B [
         fcb   $0F
         fcb   $04
         fcb   $17
         fcb   $C1 A
         fcb   $0E
         fcb   $03
         fcb   $0E
         fcb   $9A
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
         fcb   $00
         fcb   $00
         fcb   $00
