M0112    fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
M0117    fcb   $61 a
         fcb   $F0 p
         fcb   $00
         fdb   $5800    MEMPTR
         fcb   $FF
         fcb   $FF
         fcb   $FF
         fcb   $FF
M0120    fcb   $FF
         fcb   $04
         fcb   $FF
         fcb   $04
         fcb   $FF
         fcb   $04
         fcb   $FF
         fcb   $04
         fcb   $FF
         fcb   $04
         fcb   $FF
         fcb   $00
         fcb   $01
         fcb   $22 "
         fcb   $67 g
         fcb   $36 6
M0130    fcb   $5B [
         fcb   $31 1
         fcb   $67 g
         fcb   $36 6
         fcb   $FA z
         fcb   $55 U
         fcb   $01
         fcb   $22 "
         fcb   $67 g
         fcb   $40 @
         fcb   $FA z
         fcb   $70 p
         fcb   $67 g
         fcb   $40 @
         fcb   $FA z
         fcb   $55 U
M0140    fcb   $D4 T
         fcb   $94     PARAMS
         fcb   $FF
         fcb   $00
         fcb   $07
         fcb   $00
         fcb   $67 g
         fcb   $4E N
         fcb   $FA z
         fcb   $70 p
         fcb   $67 g
         fcb   $4E N
         fcb   $FA z
         fcb   $55 U
         fcb   $D4 T
         fcb   $00
M0150    fcb   $00
         fcb   $00
         fcb   $DF _
         fcb   $C0 @
         fcb   $00
         fcb   $43 C
         fcb   $67 g
         fcb   $63 c
         fcb   $F2 r
         fcb   $B3 3
         fcb   $03
         fcb   $DF _
         fcb   $C0 @
         fcb   $FA z
         fcb   $24 $
         fcb   $67 g
         fcb   $63 c
         fcb   $FA z
         fcb   $55 U
         fcb   $94
         fcb   $03
         fcb   $01
         fcb   $00
         fcb   $E3 c
         fcb   $00
         fcb   $B9 9
         fcb   $3A :
         fcb   $B7 7
         fcb   $09
         fcb   $02
         fcb   $FC
         fcb   $BF ?
         fcb   $1C
         fcb   $0A
         fcb   $B9 9
         fcb   $3A :
         fcb   $F9 y
         fcb   $A5 %
         fcb   $84
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $01
         fcb   $22 "
         fcb   $67 g
         fcb   $88
         fcb   $FA z
         fcb   $A0
         fcb   $FA z
         fcb   $70 p
         fcb   $67 g
         fcb   $88
         fcb   $FA z
         fcb   $55 U
         fcb   $D0 P
         fcb   $67 g
         fcb   $E2 b
         fcb   $00
         fcb   $00
         fcb   $63 c
         fcb   $DF _
         fcb   $C0 @
         fcb   $67 g
         fcb   $A6 &
         fcb   $F3 s
         fcb   $3D =
         fcb   $D0 P
         fcb   $67 g
         fcb   $E2 b
         fcb   $00
         fcb   $00
         fcb   $62 b
         fcb   $DF _
         fcb   $C0 @
         fcb   $67 g
         fcb   $A6 &
         fcb   $F3 s
         fcb   $3D =
         fcb   $FA z
         fcb   $70 p
         fcb   $67 g
         fcb   $A6 &
         fcb   $FA z
         fcb   $55 U
         fcb   $84
         fcb   $00
         fcb   $64 d
         fcb   $00
         fcb   $00
         fcb   $63 c
         fcb   $E3 c
         fcb   $00
         fcb   $B7 7
         fcb   $EA j
         fcb   $CF O
         fcb   $2A *
         fcb   $CE N
         fcb   $D7 W
         fcb   $CD M
         fcb   $3E >
         fcb   $CB K
         fcb   $DB [
         fcb   $B7 7
         fcb   $23 #
         fcb   $A1 !
         fcb   $12
         fcb   $00
         fcb   $0F
         fcb   $06
         fcb   $80
         fcb   $80
         fcb   $00
         fcb   $01
         fcb   $01
         fcb   $00
         fcb   $00
         fcb   $81
         fcb   $84
         fcb   $84
         fcb   $03
         fcb   $0D
         fcb   $01
         fcb   $07
         fcb   $00
         fcb   $A1
         fcb   $11
         fcb   $0D
         fcb   $5F
         fcb   $00
         fcb   $1A
         fcb   $12
         fcb   $00
         fcb   $80
         fcb   $01
         fcb   $0D
         fcb   $01
         fcb   $07
         fcb   $00
         fcb   $00
         fcb   $01
         fcb   $07
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $84
         fcb   $00
         fcb   $1E
         fcb   $06
         fcb   $03
         fcb   $60
         fcb   $00
         fcb   $5A
         fcb   $80
         fcb   $01
         fcb   $F1
         fcb   $03
         fcb   $00
         fcb   $12
M01F0    fcb   $FF
         fcb   $30 0
         fcc   "        .......SOFTWAR"

         fcb   $18
         fcb   $30 0
         fcc   "         dollar rate ="

         fcb   $18
         fcb   $30 0
         fcc   "                duty ="

         fcb   $14
         fcb   $32 2
         fcc   "* CRASMB with 6809"

         fcb   $14
         fcb   $32 2
         fcc   "* additional CPM's"

         fcb   $18
         fcb   $32 2
         fcc   "* addit CPM's with sce"

         fcb   $17
         fcb   $32 2
         fcc   "68000 "

M0280    fcc   "macro cross ass"

         fcb   $0D
         fcb   $32
         fcc   "with source"

         fcb   $0F
         fcb   $32 2
         fcc   "+ SuperSleuth"

         fcb   $13
         fcb   $32
         fcc   "+ Z80 SuperSleuth"

         fcb   $12
         fcb   $32
         fcc   "+ 6805 simulator"

         fcb   $12
         fcb   $32 2
         fcc   "+ 6502 simulator"

         fcb   $12
         fcb   $32 2
         fcc   "* HDS200 utility"

         fcb   $16
         fcb   $32 2
         fcc   " development package"

         fcb   $16
         fcb   $32 2
         fcc   "+ 6502 to 6809 trans"

         fcb   $16
         fcb   $32 2
         fcc   "+ 6800 to 6809 "

M0331    fcb   $00
         fcb   $00
         fcb   $01
         fcb   $00
         fcb   $00
         fcb   $01
         fcb   $00
         fcb   $01
         fcb   $18
         fcb   $08
         fcb   $18
         fcb   $0D
         fcb   $00
         fcb   $04
         fcb   $01
         fcb   $17
         fcb   $03
         fcb   $05
         fcb   $08
         fcb   $07
         fcb   $15
         fcb   $00
         fcb   $00
         fcb   $35 5
         fcb   $11
         fcb   $13
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $9F
         fcb   $87
         fcb   $00
         fcc   "O job control l"

M0360    fcb   $00
         fcb   $00
         fcb   $01
         fcb   $00
         fcb   $01
         fcb   $01
         fcb   $00
         fcb   $01
         fcb   $18
         fcb   $08
         fcb   $18
         fcb   $0D
         fcb   $1B
         fcb   $04
         fcb   $01
         fcb   $17
         fcb   $03
         fcb   $05
         fcb   $08
         fcb   $07
         fcb   $15
         fcb   $00
         fcb   $00
         fcb   $35 5
         fcb   $11
         fcb   $13
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $9F
         fcb   $87
         fcb   $00
M0380    fcb   $80
M0381    fcb   $80
         fcb   $80
         fcb   $80
         fcb   $80
         fcb   $0D
         fcb   $FF
         fcb   $2B +
         fcb   $2D -
         fcb   $2E .
         fcb   $FF
         fcb   $2F /
         fcb   $2A *
         fcb   $5E ^
         fcb   $2C ,
         fcb   $FF
         fcb   $28 (
         fcb   $29 )
         fcb   $FF
         fcb   $23 #
         fcb   $40 @
         fcb   $FF
         fcb   $21 !
         fcb   $FF
M0398    fcb   $FF
         fcb   $22
         fcb   $FF
         fcb   $2B +
         fcb   $2D -
         fcb   $28 (
         fcb   $2E .
         fcb   $40 @
         fcb   $23 #
         fcb   $FF
         fcb   $3E >
         fcb   $FF
M03A4    fcb   $58
         fcb   $21
         fcb   $0D
         fcb   $80
         fcb   $FF
         fcb   $80
         fcb   $80
         fcb   $80
         fcb   $80
         fcb   $FF
         fcb   $2F /
         fcb   $FF
         fcb   $FF   M03B0
         fcc   "  (X) "
         fcb   $00
M03B8    fcc   "Ready"
         fcb   $00
M03BE    fcc   "Value"
         fcb   $00
M03C4    fcc   "Label"
         fcb   $00
         fcb   $6C l
         fcb   $20
         fcb   $4D M
         fcb   $65 e
         fcb   $72 r
         fcb   $67 g
         fcb   $65 e
         fcb   $0F
         fcb   $32 2
         fcc   "+ Spell Check"
         fcb   $12
         fcb   $32 2
         fcb   $2B +
         fcb   $20
         fcb   $53 S
         fcb   $74 t
         fcb   $79 y
         fcb   $6C l
         fcb   $6F o
         fcb   $2F /
         fcb   $4D M
         fcb   $4D M
         fcb   $2F /
         fcb   $53 S
         fcb   $70 p
         fcb   $65 e
         fcb   $6C l
         fcb   $6C l
         fcb   $0C
         fcb   $32 2
         fcb   $2B +
         fcb   $20
         fcb   $44 D
         fcb   $79 y
         fcb   $6E n
         fcb   $61 a
         fcb   $63 c
         fcb   $61 a
         fcb   $6C l
         fcb   $63 c
         fcb   $10
         fcb   $32 2
         fcc   "* RMS database"
         fcb   $07
         fcb   $30 0
         fcc   "E  PR"

         fcb   $0A
         fcb   $A3 #
         fcb   $40 @
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $81

         fcb   $0A
         fcb   $A3 #
         fcb   $20
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $84

         fcb   $07
         fcb   $30 0
         fcb   $64 d
         fcb   $6F o
         fcb   $6C l
         fcb   $6C l
         fcb   $61 a

         fcb   $07
         fcb   $30 0
         fcc   "price"

         fcb   $0A
         fcb   $A0
         fcb   $48 H
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $87

         fcb   $06
         fcb   $30 0
         fcc   "ICE "

         fcb   $06
         fcb   $30 0
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20

         fcb   $03
         fcb   $30 0
         fcb   $25 %

         fcb   $04
         fcb   $30 0
         fcb   $72 r
         fcb   $20

         fcb   $03
         fcb   $30 0
         fcb   $20

         fcb   $03
         fcb   $37 7
         fcb   $2E .

         fcb   $06
         fcb   $30 0
         fcb   $20
         fcb   $4C L
         fcb   $49 I
         fcb   $53 S

         fcb   $06
         fcb   $30 0
         fcb   $20
         fcb   $65 e
         fcb   $6E n
         fcb   $64 d

         fcb   $06
         fcb   $30 0
         fcb   $20
         fcb   $75 u
         fcb   $73 s
         fcb   $65 e

         fcb   $49 I
         fcb   $20
         fcb   $16
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $87
         fcb   $20
         fcb   $08
         fcb   $48 H
         fcb   $01
         fcb   $0B
         fcb   $02
         fcb   $08
         fcb   $88
         fcb   $48 H
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $87
         fcb   $40 @
         fcb   $01
         fcb   $04
         fcb   $09
         fcb   $83
         fcb   $48 H
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $87
         fcb   $09
         fcb   $43 C
         fcb   $01
         fcb   $02
         fcb   $09
         fcb   $80
         fcb   $20
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $83
         fcb   $09
         fcb   $83
         fcb   $20
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $83
         fcb   $09
         fcb   $82
         fcb   $20
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $83
         fcb   $06
         fcb   $30 0
         fcb   $54 T
         fcb   $20
         fcb   $20
         fcb   $44 D
         fcb   $06
         fcb   $30 0
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $06
         fcb   $30 0
         fcb   $72 r
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $03
         fcb   $37 7
         fcb   $2E .

         fcb   $06
         fcb   $30 0
         fcb   $45 E
         fcb   $43 C
         fcb   $45 E
         fcb   $4D M

         fcb   $06
         fcb   $33 3
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $44 D

         fcb   $06
         fcb   $30 0
         fcb   $20
         fcb   $31 1
         fcb   $20
         fcb   $2D -
         fcb   $06
         fcb   $30 0
         fcb   $20
         fcb   $34 4
         fcb   $20
         fcb   $2D -
         fcb   $06
         fcb   $30 0
         fcb   $31 1
         fcb   $30 0
         fcb   $20
         fcb   $2D -
         fcb   $06
         fcb   $30 0
         fcb   $35 5
         fcb   $30 0
         fcb   $20
         fcb   $2D -
         fcb   $06
         fcb   $30 0
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $06
         fcb   $30 0
         fcb   $20
         fcb   $31 1
         fcb   $2D -
         fcb   $33 3
         fcb   $4C L
         fcb   $20
         fcb   $02
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $87
         fcb   $20
         fcb   $08
         fcb   $48 H
         fcb   $01
         fcb   $0B
         fcb   $02
         fcb   $08
         fcb   $88
         fcb   $48 H
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $87
         fcb   $41 A
         fcb   $07
         fcb   $03
         fcb   $40 @
         fcb   $01
         fcb   $04
         fcb   $09
         fcb   $83
         fcb   $48 H
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $87
         fcb   $09
         fcb   $43 C
         fcb   $01
         fcb   $02
         fcb   $09
         fcb   $80
         fcb   $20
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $83
         fcb   $09
         fcb   $83
         fcb   $20
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $83
         fcb   $09
         fcb   $82
         fcb   $20
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $83

         fcb   $06
         fcb   $30 0
         fcc   "BER "

         fcb   $06
         fcb   $30 0
         fcb   $49 I
         fcb   $53 S
         fcb   $43 C
         fcb   $4F O

         fcb   $06
         fcb   $30
         fcc   '  3 '

         fcb   $05
         fcb   $30
         fcc   '  9'

         fcb   $05
         fcb   $30
         fcc   ' 49'

M0562    fcc   " December 13, 1983"
         fcb   $00

M0575    fdb   $0800   Location of program
M0577    fcb   $30 0
         fcb   $20
         fcb   $31 1
         fcb   $39 9
         fcb   $38 8

         fcb   $06
         fcb   $30 0
         fcb   $55 U
         fcb   $4E N
         fcb   $54 T
         fcb   $20

         fcb   $0A,$A0,$20,$00,$00,$00,$00,$00,$00,$85
         fcb   $0A,$A0,$0C,$00,$00,$00,$00,$00,$00,$86

         fcb   $0A
         fcb   $A0
         fcb   $20
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $86
         fcb   $0A
         fcb   $A0
         fcb   $34 4
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $86
         fcb   $06
         fcb   $30 0
         fcb   $6C l
         fcb   $65 e
         fcb   $72 r
         fcb   $20
         fcb   $06
         fcb   $30 0
         fcb   $20
         fcb   $34 4
         fcb   $2D -
         fcb   $39 9
         fcb   $4C L
         fcb   $20
         fcb   $5C \
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $86
         fcb   $20
         fcb   $08
         fcb   $48 H
         fcb   $01
         fcb   $0B
         fcb   $02
         fcb   $08
         fcb   $88
         fcb   $48 H
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $87
         fcb   $41 A
         fcb   $07
         fcb   $04
         fcb   $40 @
         fcb   $01
         fcb   $04
         fcb   $09
         fcb   $83
         fcb   $48 H
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $87
         fcb   $09
         fcb   $43 C
         fcb   $01
         fcb   $02
         fcb   $09
         fcb   $80
         fcb   $20
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $83
         fcb   $09
         fcb   $83
         fcb   $20
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $83
         fcb   $09
         fcb   $82
         fcb   $20
         fcb   $00
         fcb   $00
         fcb   $00
M05FE    fcb   $01
M05FF    fcb   $00
M0600    fcb   $00
         fcb   $24 $
         fcb   $03
         fcb   $30 0
         fcb   $33 3
         fcb   $06
         fcb   $30 0
         fcb   $54 T

* Out of memory routine
M0608    ldy   #$004E
         leax  >M0629,pcr
         lda   #$02
         os9   I$Write
         clra
         leax  >M0629,pcr
         ldy   #$0001
         os9   I$Read
         ldu   >M0575,pcr
         jmp   >L3AEA-PGBEGIN,u   >$3AD5,u  = L3AEA

M0629    fcb   $0D
         fcb   $0A
         fcb   $0A
M062C    fcc   "OUT OF MEMORY- Worksheet not completely loaded."
         fcb   $0D
         fcb   $0A
M065D    fcc   "Press any key to continue."

M0677    fcb   $30 0
         fcb   $2D -
         fcb   $34 4
         fcb   $4C L
         fcb   $20
         fcb   $48 H
         fcb   $00
         fcb   $00
         fcb   $00
* Default printer name (60 bytes)
M0680    fcc   "/P "
         fcb   $00
         fcb   $20
         fcb   $08
         fcb   $48 H
         fcb   $01
         fcb   $0B
         fcb   $02
         fcb   $08
         fcb   $88
         fcb   $48 H
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $87
         fcb   $41 A
         fcb   $07
         fcb   $05
         fcb   $40 @
         fcb   $01
         fcb   $04
         fcb   $09
         fcb   $83
         fcb   $48 H
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $87
         fcb   $09
         fcb   $43 C
         fcb   $01
         fcb   $02
         fcb   $09
         fcb   $80
         fcb   $20
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $83
         fcb   $09
         fcb   $83
         fcb   $20
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $83
         fcb   $09
         fcb   $82
         fcb   $20
         fcb   $00

M06C0    fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $83
         fcb   $06
         fcb   $30 0
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $06
         fcb   $30 0
         fcb   $39 9
         fcb   $20
M06D0    fcb   $20
         fcb   $20
         fcb   $03
         fcb   $37 7
         fcb   $2E .
         fcb   $06
         fcb   $30 0
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $20
         fcb   $06
         fcb   $30 0
         fcb   $35 5
         fcb   $30 0
         fcb   $2D -
         fcb   $39 9
         fcb   $4C L
         fcb   $20
         fcb   $34 4
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $86
         fcb   $20
         fcb   $08
         fcb   $48 H
         fcb   $01
         fcb   $0B
         fcb   $02
         fcb   $08
         fcb   $88
         fcb   $48 H
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $87
         fcb   $41 A
         fcb   $07
         fcb   $06
         fcb   $40 @
         fcb   $01

M0700    fcb   $1B,$41,$06,$0F    Cyrsor XY
         fcc   " (Press any key to continue)  "
         fcb   $FF
         fcb   $09
         fcb   $82
         fcb   $20
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $00
         fcb   $83
         fcb   $06
         fcb   $30 0
         fcb   $20
* Address $0730
 fcb $20,$20,$20,$04,$30,$39,$20,$03,$37,$2E,$06,$30,$20,$4F,$45,$4D
 fcb $0A,$A0,$70,$00,$00,$00,$00,$00,$00,$86,$4C,$20,$0C,$00,$00,$00
 fcb $00,$00,$00,$86,$20,$08,$48,$01,$0B,$02,$08,$88,$48,$00,$00,$00
 fcb $00,$00,$00,$87,$41,$0D,$09,$40,$01,$04,$09,$83,$48,$00,$00,$00
 fcb $00,$00,$00,$87,$09,$43,$01,$02,$09,$80,$20,$00,$00,$00,$00,$00
 fcb $00,$83,$09,$83,$20,$00,$00,$00,$00,$00,$00,$83,$09,$82,$20,$00
 fcb $00,$00,$00,$00,$00,$83,$04,$10,$20,$25,$0A,$A0,$48,$00,$00,$00
 fcb $00,$00,$00,$87,$0A,$A0,$48,$00,$00,$00,$00,$00,$00,$87,$0A,$A0
 fcb $48,$00,$00,$00,$00,$00,$00,$87,$0A,$A0,$48,$00,$00,$00,$00,$00
 fcb $00,$87,$0A,$A0,$48,$00,$00,$00,$00,$00,$00,$87,$0A,$A0,$48,$00
 fcb $00,$00,$00,$00,$00,$87,$0A,$A0,$48,$00,$00,$00,$00,$00,$00,$87
 fcb $0A,$A0,$48,$00,$00,$00,$00,$00,$00,$87,$0A,$A0,$48,$00,$00,$00
 fcb $00,$00,$00,$87,$0A,$A0,$48,$00,$00,$00,$00,$00,$00,$87,$0A,$A0
 fcb $48,$00,$00,$00,$00,$00,$00,$87,$0A,$A0,$48,$00,$00,$00,$00,$00
 fcb $00,$87,$0A,$A0,$48,$00,$00,$00,$00,$00,$00,$87,$0A,$A0,$48,$00
 fcb $00,$00,$00,$00,$00,$87,$0A,$A0,$48,$00,$00,$00,$00,$00,$00,$87
 fcb $0A,$A0,$48,$00,$00,$00,$00,$00,$00,$87,$0A,$A0,$48,$00,$00,$00
 fcb $00,$00,$00,$87,$0A,$A0,$48,$00,$00,$00,$00,$00,$00,$87,$0A,$A0
 fcb $48,$00,$00,$00,$00,$00,$00,$87,$0A,$A0,$48,$00,$00,$00,$00,$00
 fcb $00,$87,$0A,$A0,$48,$00,$00,$00,$00,$00,$00,$87,$0A,$A0,$48,$00
 fcb $00,$00,$00,$00,$00,$87,$0A,$A0,$48,$00,$00,$00,$00,$00,$00,$87
 fcb $0A,$A0,$48,$00,$00,$00,$00,$00,$00,$87,$49,$20,$16,$00,$00,$00
 fcb $00,$00,$00,$87,$20,$08,$48,$01,$0C,$02,$08,$88,$48,$00,$00,$00
 fcb $00,$00,$00,$87,$40,$01,$04,$09,$83,$48,$00,$00,$00,$00,$00,$00
 fcb $87,$09,$43,$01,$02,$09,$80,$20,$00,$00,$00,$00,$00,$00,$83,$09
 fcb $83,$20,$00,$00,$00,$00,$00,$00,$83,$09,$82,$20,$00,$00,$00,$00
 fcb $00,$00,$83,$49,$20,$16,$00,$00,$00,$00,$00,$00,$87,$20,$08,$48
 fcb $01,$0D,$02,$08,$88,$48,$00,$00,$00,$00,$00,$00,$87,$40,$01,$04
 fcb $09,$83,$48,$00,$00,$00,$00,$00,$00,$87,$09,$43,$01,$02,$09,$80
 fcb $20,$00,$00,$00,$00,$00,$00,$83,$09,$83,$20,$00,$00,$00,$00,$00
 fcb $00,$83,$09,$82,$20,$00,$00,$00,$00,$00,$00,$83,$49,$20,$16,$00
 fcb $00,$00,$00,$00,$00,$87,$20,$08,$48,$01,$0F,$02,$08,$88,$48,$00
 fcb $00,$00,$00,$00,$00,$87,$40,$01,$04,$09,$83,$48,$00,$00,$00,$00
 fcb $00,$00,$87,$09,$43,$01,$02,$09,$80,$20,$00,$00,$00,$00,$00,$00
 fcb $83,$09,$83,$20,$00,$00,$00,$00,$00,$00,$83,$09,$82,$20,$00,$00
 fcb $00,$00,$00,$00,$83,$49,$20,$16,$00,$00,$00,$00,$00,$00,$87,$20
 fcb $08,$48,$01,$10,$02,$08,$88,$48,$00,$00,$00,$00,$00,$00,$87,$40
 fcb $01,$04,$09,$83,$48,$00,$00,$00,$00,$00,$00,$87,$09,$43,$01,$02
 fcb $09,$80,$20,$00,$00,$00,$00,$00,$00,$83,$09,$83,$20,$00,$00,$00
 fcb $00,$00,$00,$83,$09,$82,$20,$00,$00,$00,$00,$00,$00,$83,$49,$20
 fcb $16,$00,$00,$00,$00,$00,$00,$87,$20,$08,$48,$01,$12,$02,$08,$88
 fcb $48,$00,$00,$00,$00,$00,$00,$87,$40,$01,$04,$09,$A0,$00,$01,$59
 fcb $00,$00,$0F,$FD,$A0,$A0,$00,$00,$59,$59,$80,$02,$3F,$59,$8D,$D3

* Address $09E0
         fcb   $00
         fcb   $01
         fcb   $80
         fcb   $03
         fcb   $3F ?
         fcb   $59 Y
         fcb   $58 X
         fcb   $00
         fcb   $32 2
         fcb   $00
         fcb   $8D
         fcb   $3D =
         fcb   $8C
         fcb   $E5 e
         fcb   $64 d
         fcb   $5B [

M09F0    nop
         nop
         nop
         nop
         nop
         nop
         nop
         nop
         nop
         nop
         nop
         nop
         nop
         nop
         nop
         nop
         nop
         nop
         nop
         nop
         nop
M0A05    lbra  M0A27

* Entry point for start routine in dynacalc program
* X contains the program counter a few instructions before the jump.
M0A08    lbra  M0A21

         pshs  x,a
         tfr   pc,x
         leax  >-$5A0F,x     Is this at M0A0F ?
         stx   >M0575,pcr
         lda   #$FF
         sta   >$0143,u
         puls  x,a
         bra   M0A74

M0A21    cmpd  #$0473   version number test
         beq   M0A6A
M0A27    lda   #$02
         leax  >M0A38,pcr
         ldy   #$FFFF
         os9   I$WritLn
         clrb
         os9   F$Exit

M0A38    fcc   "DYNACALC and DYNACALC.TRM are different versions."
         fcb   $0D

M0A6A    leax  >PGBEGIN-PCSAVEPT,x   PGBEGIN-PCSAVEPT = $15
         stx   >M0575,pcr
         puls  u,y,x,b,a
M0A74    std   >$01C1,u
         tfr   dp,a
         inca
         tfr   a,dp
         stx   <PARAMS
         stu   <MEMPTR   beginning of data
         leax  >M0280,u
         stx   <$00E9
         ldx   #$0700
         stx   <$0044
         clr   <$00ED
         clr   <$00EE
         clr   <$0019
         clr   <$00A7
         clr   >M06C0,pcr
         ldu   <MEMPTR   beginning of data
         leax  >M09F0,u
         stx   <$0017
         tfr   x,s
         leax  >M0331,u
         stx   <u0030
         leax  <$2F,x  Buffer at M0360
         clra
         clrb
         os9   I$GetStt
         bra   M0AB2
M0AB2
         leax  >M0680,pcr
         lda   #$02
         os9   I$Open
         bcc   M0AD0
         leax  >M0680,pcr
         lda   #$02
         ldb   #%00011011 File permissions for new file
         os9   I$Create
         bcc   M0AD0
         clr   >M0680,pcr
         bra   M0B05

M0AD0    sta   <$0012   data file path number
M0AD2    ldx   <u0030
         clrb
         os9   I$GetStt
         bcs   M0AFA
         ldx   <u0030
         clrb
         lda   ,x
M0ADF    beq   M0AF4
         deca
         bne   M0AFA
         lda   <$0012   data file path number
         ldb   #$02      Get file size
         os9   I$GetStt
         bcs   M0AFA
         os9   I$Seek
         bcs   M0AFA
         ldb   #$FF
M0AF4    stb   <$0013
         bne   M0B05
         bra   M0AFE
M0AFA    clr   >M0680,pcr
M0AFE    lda   <$0012   data file path number
M0B00    os9   I$Close
         clr   <$0012   data file path number
M0B05    ldx   <$0030
         os9   F$Time
         leay  >M0562,pcr
         lda   $01,x
         deca
         cmpa  #11
         bls   M0B16
         clra
M0B16    ldb   #$09
         mul
         leau  >MONTHS,pcr  Calendar months
         leau  d,u
M0B1F    ldb   #$09
M0B21    lda   ,u+
         sta   ,y+
         decb
         bne   M0B21
         lda   #$20
         sta   ,y+
         ldb   $02,x
         bsr   M0B44
         ldd   #$2C20
         std   ,y++
         ldd   #$3139   string '19'
         std   ,y++
         ldx   <$0030
         ldb   ,x
         bsr   M0B44
         clr   ,y
         bra   M0B60

M0B44    clra
         ldu   #$0700
         stu   <$0044
         ldu   >M0575,pcr
         jsr   L4795-PGBEGIN,u   >$4780,u  = L4795
         ldu   #$0700
         stu   <$0044
         ldd   <MEMPTR
         leau  d,u
         ldd   $03,u
         std   ,y++
         rts

M0B60    ldy   >M0575,pcr
         jsr   >L0E44-PGBEGIN,y     >$0E2F,y
         ldb   $01,x
         bne   M0B73
         ldb   >M00F8,pcr
         beq   M0B77
M0B73    stb   >M00FA,pcr
M0B77    clr   $0C,x
         tst   <$0043
         bne   M0B88
         clr   $0F,x
M0B7F    clr   <$10,x
         clr   <$11,x
         clr   <$16,x
M0B88    clr   $04,x
         jsr   >L0E4F-PGBEGIN,y     >$0E3A,y
         ldu   #$01F1
         stu   <$00EB
         clr   <$00E0
         clr   <$00E8
         clr   <$00C4
         tst   >M00B8,pcr    Cursor control sequences
         bpl   M0BA1
M0B9F    dec   <$000E
M0BA1    tst   >M00F7,pcr
         bne   M0BAD
         lda   #$04
         sta   >M00F7,pcr
M0BAD    lda   #$90
         ldy   >M0575,pcr
         jsr   >L0DC4-PGBEGIN,y   >$0DAF,y
         lda   #$FF
         sta   <$00F0
         jsr   >L0D36-PGBEGIN,y

 ifeq ISSUE-STANDARD
* Copy terminal name to banner
         lda   #$0F
         leau  >M00DE,pcr
         leax  >TRMBANNR,pcr
M0BE6    ldb   a,u
         stb   a,x
         deca
         bpl   M0BE6
 endc

M0BC0    ldd   <$000D    See M10D in trmfile
         subd  #$0A26    Line 10 column 38
         lsra              Change to line 5
         lsrb              Change to column 19
         std   <$00BD
         ldb   #4   Number of segments to print
         leau  >BANNER,pcr    Write DYNACALC on startup
M0BCF    jsr   >L0D57-PGBEGIN,y     Move cursor
         jsr   >L1AB9-PGBEGIN,y     output string pointed to in U
         inc   <$00BD     Add 1 to line
         inc   <$00BD     Add 1 to line
         decb
         bne   M0BCF
         jsr   >L0D57-PGBEGIN,y  Move cursor
M0BE2    ldd   <$00C1
         cmpd  #$0001
         bls   M0C35
         ldy   <PARAMS
         lda   ,y
         cmpa  #$2D
         beq   M0C25
         ldb   #$0C
         ldx   <$00E9

M0BF7    lda   ,y+
         cmpa  #$20
         beq   M0C1D
         cmpa  #$0D
         beq   M0C0A   Found end of parameters
         incb
         stb   <$00ED
         sta   b,x
         cmpb  #'/
         bne   M0BF7
M0C0A    tst   <$00ED
         beq   M0C35
         leau  >MLOAD,pcr     Write Loading
         ldy   >M0575,pcr
         jsr   >L1AB9-PGBEGIN,y   output string pointed to in U
         bra   M0C5B

M0C1D    lda   ,y+
         cmpa  #$20
         beq   M0C1D
         leay  -$01,y
M0C25    ldb   $01,y
         andb  #$5F
         cmpd  #$2D48  -H  deletes builtin help messages
         bne   M0C0A
         sta   >M00FB,pcr
         bra   M0C0A

M0C35    ldy   >M0575,pcr
         jsr   >L1AB9-PGBEGIN,y  output string pointed to in U
         ldb   #$04
         stb   <$0025
         clr   >M05FF,pcr
         clr   >M05FE,pcr
M0C4A    jsr   >L1AC5-PGBEGIN,y  Wait for input
         bne   M0C54
         dec   <$0025
         bne   M0C4A
M0C54    tst   <$0043
         beq   M0C5B
         lbsr  $3400  Dynacalc.trm is only $3200 bytes
M0C5B    ldb   #$08
         leax  >M0100,pcr   Start of keys
         leau  >M0CCB,pcr
         ldy   <MEMPTR
M0C68    lda   ,x+
         pshs  x,b,a
         ldd   ,u++
         leax  d,y
         lda   ,s
         sta   ,x
         ldd   ,u++
         leax  d,y
         puls  a
         sta   ,x
         puls  x,b
         decb
         bne   M0C68
         ldx   >M0575,pcr
         leay  >$0F00,y
         ldd   $06,y
         sta   <u001D
         clr   <$007D
         lsra  
         rorb  
         ror   <$007D
         std   <$006C
         ldd   $06,y
         leau  d,y
         ldx   <PARAMS
         leax  $01,x
         pshs  x
         ldx   <MEMPTR   beginning of data
         tst   >M00FB,x  Keep helps ?
         puls  x
         bne   M0CB6
         leax  -$02,x
         clr   <u001D  Clear helps flag
         ldy   >M0575,pcr
         jsr   >L3AFF-PGBEGIN,y   >$3AEA,y
M0CB6    nop
         tfr   x,d
         std   <$001E
         subd  <$0017
         lsra
         rorb
         addd  <$0017
         std   <$0023
         ldu   >M0575,pcr
         jmp   >L4EC7-PGBEGIN,u    >$4EB2,u


M0CCB    fdb   $0381  Up-arrow
         fdb   $03A9
         fdb   $0382  Down-arrow
         fdb   $03AA
         fdb   $0383  Left-arrow
         fdb   $03AB
         fdb   $0384  Right-arrow
         fdb   $03AC
         fdb   $03A7  Home key
         fdb   $03A7
         fdb   $03A4
         fdb   $03A4
         fdb   $0380
         fdb   $0380
         fdb   $0380
         fdb   $0380

MONTHS   fcc   "  January"
         fcc   " February"
         fcc   "    March"
         fcc   "    April"
         fcc   "      May"
         fcc   "     June"
         fcc   "     July"
         fcc   "   August"
         fcc   "September"
         fcc   "  October"
         fcc   " November"
         fcc   " December"
 ifeq ISSUE-STANDARD
BANNER   fcc   "          **** DYNACALC ****"
         fcb   0
         fcc   "        Version Number - 4.7:3"
         fcb   0
         fcc   "Copyright (C) 1982 by Scott Schaeferle"
         fcb   0
         fcc   "    Customized for the "
TRMBANNR fcc   "ADDS Viewpoint   "
         fcb   0
         fcc   "        (Press any key to continue)"
         fcb   0
MLOAD    fcc   "                    Loading "
         fcb   0
 else
BANNER   fcc   "      **** DYNACALC ****"
         fcb   0
         fcc   "                              "
         fcb   0
         fcc   " "
         fcb   0
         fcc   "      for the Dragon 64"
         fcb   0
         fcc   " (Press any key to continue)  "
         fcb   0
MLOAD    fcc   "      Loading "
         fcb   0
 endc
