#!/bin/sh

cd target

java -Dorg.slf4j.simpleLogger.log.org.roug.usim.Acia6850=debug \
     -Dorg.slf4j.simpleLogger.showDateTime=true \
     -Dorg.slf4j.simpleLogger.showLogName=false \
     -Dorg.slf4j.simpleLogger.showShortLogName=true \
  -jar ../../v6809/target/v6809-1.0-SNAPSHOT-jar-with-dependencies.jar -c mc6850.properties
